// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: accounts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentBalance   int64                  `protobuf:"varint,3,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	AvailableBalance int64                  `protobuf:"varint,4,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	HoldingBalance   int64                  `protobuf:"varint,5,opt,name=holding_balance,json=holdingBalance,proto3" json:"holding_balance,omitempty"`
	Metadata         *Account_Metadata      `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Currency         string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type             string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Category         string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	IsSystemAccount  bool                   `protobuf:"varint,12,opt,name=is_system_account,json=isSystemAccount,proto3" json:"is_system_account,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetCurrentBalance() int64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *Account) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *Account) GetHoldingBalance() int64 {
	if x != nil {
		return x.HoldingBalance
	}
	return 0
}

func (x *Account) GetMetadata() *Account_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Account) GetIsSystemAccount() bool {
	if x != nil {
		return x.IsSystemAccount
	}
	return false
}

type AccountList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Query         *AccountQuery          `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountList) Reset() {
	*x = AccountList{}
	mi := &file_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountList) ProtoMessage() {}

func (x *AccountList) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountList.ProtoReflect.Descriptor instead.
func (*AccountList) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *AccountList) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *AccountList) GetQuery() *AccountQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type AccountQuery struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ids             []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartDate       string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate         string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Type            string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Name            string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	PlatformAccount bool                   `protobuf:"varint,8,opt,name=platform_account,json=platformAccount,proto3" json:"platform_account,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountQuery) Reset() {
	*x = AccountQuery{}
	mi := &file_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountQuery) ProtoMessage() {}

func (x *AccountQuery) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountQuery.ProtoReflect.Descriptor instead.
func (*AccountQuery) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *AccountQuery) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *AccountQuery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountQuery) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AccountQuery) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *AccountQuery) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccountQuery) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountQuery) GetPlatformAccount() bool {
	if x != nil {
		return x.PlatformAccount
	}
	return false
}

type AccountUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Query         *AccountQuery          `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountUpdate) Reset() {
	*x = AccountUpdate{}
	mi := &file_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUpdate) ProtoMessage() {}

func (x *AccountUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUpdate.ProtoReflect.Descriptor instead.
func (*AccountUpdate) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *AccountUpdate) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountUpdate) GetQuery() *AccountQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postings      []*Transfer_Posting    `protobuf:"bytes,1,rep,name=postings,proto3" json:"postings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *Transfer) GetPostings() []*Transfer_Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *TransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransferRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRef) Reset() {
	*x = TransferRef{}
	mi := &file_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRef) ProtoMessage() {}

func (x *TransferRef) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRef.ProtoReflect.Descriptor instead.
func (*TransferRef) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *TransferRef) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type BulkCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreate) Reset() {
	*x = BulkCreate{}
	mi := &file_accounts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreate) ProtoMessage() {}

func (x *BulkCreate) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreate.ProtoReflect.Descriptor instead.
func (*BulkCreate) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{7}
}

func (x *BulkCreate) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type Account_Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account_Metadata) Reset() {
	*x = Account_Metadata{}
	mi := &file_accounts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account_Metadata) ProtoMessage() {}

func (x *Account_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account_Metadata.ProtoReflect.Descriptor instead.
func (*Account_Metadata) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Account_Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account_Metadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Transfer_Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rate          int64                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	SourceId      string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestinationId string                 `protobuf:"bytes,5,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	Source        *Account               `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Destination   *Account               `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	Commited      bool                   `protobuf:"varint,8,opt,name=commited,proto3" json:"commited,omitempty"`
	TransferRef   string                 `protobuf:"bytes,9,opt,name=transfer_ref,json=transferRef,proto3" json:"transfer_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer_Posting) Reset() {
	*x = Transfer_Posting{}
	mi := &file_accounts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer_Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer_Posting) ProtoMessage() {}

func (x *Transfer_Posting) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer_Posting.ProtoReflect.Descriptor instead.
func (*Transfer_Posting) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Transfer_Posting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transfer_Posting) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Transfer_Posting) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer_Posting) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Transfer_Posting) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *Transfer_Posting) GetSource() *Account {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Transfer_Posting) GetDestination() *Account {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Transfer_Posting) GetCommited() bool {
	if x != nil {
		return x.Commited
	}
	return false
}

func (x *Transfer_Posting) GetTransferRef() string {
	if x != nil {
		return x.TransferRef
	}
	return ""
}

var File_accounts_proto protoreflect.FileDescriptor

const file_accounts_proto_rawDesc = "" +
	"\n" +
	"\x0eaccounts.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x03\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fcurrent_balance\x18\x03 \x01(\x03R\x0ecurrentBalance\x12+\n" +
	"\x11available_balance\x18\x04 \x01(\x03R\x10availableBalance\x12'\n" +
	"\x0fholding_balance\x18\x05 \x01(\x03R\x0eholdingBalance\x12-\n" +
	"\bmetadata\x18\x06 \x01(\v2\x11.Account.MetadataR\bmetadata\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12*\n" +
	"\x11is_system_account\x18\f \x01(\bR\x0fisSystemAccount\x1a2\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"X\n" +
	"\vAccountList\x12$\n" +
	"\baccounts\x18\x01 \x03(\v2\b.AccountR\baccounts\x12#\n" +
	"\x05query\x18\x02 \x01(\v2\r.AccountQueryR\x05query\"\xe1\x01\n" +
	"\fAccountQuery\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12)\n" +
	"\x10platform_account\x18\b \x01(\bR\x0fplatformAccount\"X\n" +
	"\rAccountUpdate\x12\"\n" +
	"\aaccount\x18\x01 \x01(\v2\b.AccountR\aaccount\x12#\n" +
	"\x05query\x18\x02 \x01(\v2\r.AccountQueryR\x05query\"\xd2\x02\n" +
	"\bTransfer\x12-\n" +
	"\bpostings\x18\x01 \x03(\v2\x11.Transfer.PostingR\bpostings\x1a\x96\x02\n" +
	"\aPosting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x03R\x04rate\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x05 \x01(\tR\rdestinationId\x12 \n" +
	"\x06source\x18\x06 \x01(\v2\b.AccountR\x06source\x12*\n" +
	"\vdestination\x18\a \x01(\v2\b.AccountR\vdestination\x12\x1a\n" +
	"\bcommited\x18\b \x01(\bR\bcommited\x12!\n" +
	"\ftransfer_ref\x18\t \x01(\tR\vtransferRef\"D\n" +
	"\x10TransferResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1f\n" +
	"\vTransferRef\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"2\n" +
	"\n" +
	"BulkCreate\x12$\n" +
	"\baccounts\x18\x01 \x03(\v2\b.AccountR\baccounts2\xdb\x03\n" +
	"\x0eAccountService\x12*\n" +
	"\vGetAccounts\x12\r.AccountQuery\x1a\f.AccountList\x12 \n" +
	"\n" +
	"GetAccount\x12\b.Account\x1a\b.Account\x12#\n" +
	"\rCreateAccount\x12\b.Account\x1a\b.Account\x12*\n" +
	"\x11BulkCreateAccount\x12\v.BulkCreate\x1a\b.Account\x12-\n" +
	"\rUpdateAccount\x12\x0e.AccountUpdate\x1a\f.AccountList\x12,\n" +
	"\rDeleteAccount\x12\r.AccountQuery\x1a\f.AccountList\x121\n" +
	"\x11TransferAndCommit\x12\t.Transfer\x1a\x11.TransferResponse\x125\n" +
	"\x15TransferWithoutCommit\x12\t.Transfer\x1a\x11.TransferResponse\x120\n" +
	"\rTranferCommit\x12\f.TransferRef\x1a\x11.TransferResponse\x121\n" +
	"\x0eTransferCancel\x12\f.TransferRef\x1a\x11.TransferResponseB\x1eZ\x1cgithub.com/kvbo/protobufs;pbb\x06proto3"

var (
	file_accounts_proto_rawDescOnce sync.Once
	file_accounts_proto_rawDescData []byte
)

func file_accounts_proto_rawDescGZIP() []byte {
	file_accounts_proto_rawDescOnce.Do(func() {
		file_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)))
	})
	return file_accounts_proto_rawDescData
}

var file_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_accounts_proto_goTypes = []any{
	(*Account)(nil),               // 0: Account
	(*AccountList)(nil),           // 1: AccountList
	(*AccountQuery)(nil),          // 2: AccountQuery
	(*AccountUpdate)(nil),         // 3: AccountUpdate
	(*Transfer)(nil),              // 4: Transfer
	(*TransferResponse)(nil),      // 5: TransferResponse
	(*TransferRef)(nil),           // 6: TransferRef
	(*BulkCreate)(nil),            // 7: BulkCreate
	(*Account_Metadata)(nil),      // 8: Account.Metadata
	(*Transfer_Posting)(nil),      // 9: Transfer.Posting
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_accounts_proto_depIdxs = []int32{
	8,  // 0: Account.metadata:type_name -> Account.Metadata
	10, // 1: Account.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: AccountList.accounts:type_name -> Account
	2,  // 3: AccountList.query:type_name -> AccountQuery
	0,  // 4: AccountUpdate.account:type_name -> Account
	2,  // 5: AccountUpdate.query:type_name -> AccountQuery
	9,  // 6: Transfer.postings:type_name -> Transfer.Posting
	0,  // 7: BulkCreate.accounts:type_name -> Account
	0,  // 8: Transfer.Posting.source:type_name -> Account
	0,  // 9: Transfer.Posting.destination:type_name -> Account
	2,  // 10: AccountService.GetAccounts:input_type -> AccountQuery
	0,  // 11: AccountService.GetAccount:input_type -> Account
	0,  // 12: AccountService.CreateAccount:input_type -> Account
	7,  // 13: AccountService.BulkCreateAccount:input_type -> BulkCreate
	3,  // 14: AccountService.UpdateAccount:input_type -> AccountUpdate
	2,  // 15: AccountService.DeleteAccount:input_type -> AccountQuery
	4,  // 16: AccountService.TransferAndCommit:input_type -> Transfer
	4,  // 17: AccountService.TransferWithoutCommit:input_type -> Transfer
	6,  // 18: AccountService.TranferCommit:input_type -> TransferRef
	6,  // 19: AccountService.TransferCancel:input_type -> TransferRef
	1,  // 20: AccountService.GetAccounts:output_type -> AccountList
	0,  // 21: AccountService.GetAccount:output_type -> Account
	0,  // 22: AccountService.CreateAccount:output_type -> Account
	0,  // 23: AccountService.BulkCreateAccount:output_type -> Account
	1,  // 24: AccountService.UpdateAccount:output_type -> AccountList
	1,  // 25: AccountService.DeleteAccount:output_type -> AccountList
	5,  // 26: AccountService.TransferAndCommit:output_type -> TransferResponse
	5,  // 27: AccountService.TransferWithoutCommit:output_type -> TransferResponse
	5,  // 28: AccountService.TranferCommit:output_type -> TransferResponse
	5,  // 29: AccountService.TransferCancel:output_type -> TransferResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_accounts_proto_init() }
func file_accounts_proto_init() {
	if File_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounts_proto_goTypes,
		DependencyIndexes: file_accounts_proto_depIdxs,
		MessageInfos:      file_accounts_proto_msgTypes,
	}.Build()
	File_accounts_proto = out.File
	file_accounts_proto_goTypes = nil
	file_accounts_proto_depIdxs = nil
}
