// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: accounts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug             string                 `protobuf:"bytes,13,opt,name=slug,proto3" json:"slug,omitempty"`
	CurrentBalance   int64                  `protobuf:"varint,3,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	AvailableBalance int64                  `protobuf:"varint,4,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	HoldingBalance   int64                  `protobuf:"varint,5,opt,name=holding_balance,json=holdingBalance,proto3" json:"holding_balance,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Currency         string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type             string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Category         string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	IsSystemAccount  *bool                  `protobuf:"varint,12,opt,name=is_system_account,json=isSystemAccount,proto3,oneof" json:"is_system_account,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Account) GetCurrentBalance() int64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *Account) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *Account) GetHoldingBalance() int64 {
	if x != nil {
		return x.HoldingBalance
	}
	return 0
}

func (x *Account) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Account) GetIsSystemAccount() bool {
	if x != nil && x.IsSystemAccount != nil {
		return *x.IsSystemAccount
	}
	return false
}

type AccountList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Query         *AccountQuery          `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountList) Reset() {
	*x = AccountList{}
	mi := &file_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountList) ProtoMessage() {}

func (x *AccountList) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountList.ProtoReflect.Descriptor instead.
func (*AccountList) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *AccountList) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *AccountList) GetQuery() *AccountQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type AccountQuery struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ids             []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Status          *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	StartDate       *string                `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate         *string                `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	Type            *string                `protobuf:"bytes,5,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Currency        *string                `protobuf:"bytes,6,opt,name=currency,proto3,oneof" json:"currency,omitempty"`
	Name            *string                `protobuf:"bytes,7,opt,name=name,proto3,oneof" json:"name,omitempty"`
	IsSystemAccount *bool                  `protobuf:"varint,8,opt,name=is_system_account,json=isSystemAccount,proto3,oneof" json:"is_system_account,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountQuery) Reset() {
	*x = AccountQuery{}
	mi := &file_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountQuery) ProtoMessage() {}

func (x *AccountQuery) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountQuery.ProtoReflect.Descriptor instead.
func (*AccountQuery) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *AccountQuery) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *AccountQuery) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *AccountQuery) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *AccountQuery) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *AccountQuery) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AccountQuery) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *AccountQuery) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AccountQuery) GetIsSystemAccount() bool {
	if x != nil && x.IsSystemAccount != nil {
		return *x.IsSystemAccount
	}
	return false
}

type AccountIn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug            string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Type            string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Category        string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	IsSystemAccount *bool                  `protobuf:"varint,7,opt,name=is_system_account,json=isSystemAccount,proto3,oneof" json:"is_system_account,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountIn) Reset() {
	*x = AccountIn{}
	mi := &file_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountIn) ProtoMessage() {}

func (x *AccountIn) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountIn.ProtoReflect.Descriptor instead.
func (*AccountIn) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *AccountIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountIn) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AccountIn) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AccountIn) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountIn) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccountIn) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AccountIn) GetIsSystemAccount() bool {
	if x != nil && x.IsSystemAccount != nil {
		return *x.IsSystemAccount
	}
	return false
}

type AccountUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountIn             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Query         *AccountQuery          `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountUpdate) Reset() {
	*x = AccountUpdate{}
	mi := &file_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUpdate) ProtoMessage() {}

func (x *AccountUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUpdate.ProtoReflect.Descriptor instead.
func (*AccountUpdate) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *AccountUpdate) GetAccount() *AccountIn {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountUpdate) GetQuery() *AccountQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rate          int64                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	SourceId      string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestinationId string                 `protobuf:"bytes,5,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	Source        *Account               `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Destination   *Account               `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	Commited      bool                   `protobuf:"varint,8,opt,name=commited,proto3" json:"commited,omitempty"`
	TransferRef   string                 `protobuf:"bytes,9,opt,name=transfer_ref,json=transferRef,proto3" json:"transfer_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *Posting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Posting) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Posting) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Posting) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Posting) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *Posting) GetSource() *Account {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Posting) GetDestination() *Account {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Posting) GetCommited() bool {
	if x != nil {
		return x.Commited
	}
	return false
}

func (x *Posting) GetTransferRef() string {
	if x != nil {
		return x.TransferRef
	}
	return ""
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postings      []*Posting             `protobuf:"bytes,1,rep,name=postings,proto3" json:"postings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *Transfer) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_accounts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{7}
}

func (x *TransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransferRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRef) Reset() {
	*x = TransferRef{}
	mi := &file_accounts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRef) ProtoMessage() {}

func (x *TransferRef) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRef.ProtoReflect.Descriptor instead.
func (*TransferRef) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{8}
}

func (x *TransferRef) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type BulkCreateAccounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountIn           `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateAccounts) Reset() {
	*x = BulkCreateAccounts{}
	mi := &file_accounts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateAccounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateAccounts) ProtoMessage() {}

func (x *BulkCreateAccounts) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateAccounts.ProtoReflect.Descriptor instead.
func (*BulkCreateAccounts) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{9}
}

func (x *BulkCreateAccounts) GetAccounts() []*AccountIn {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_accounts_proto protoreflect.FileDescriptor

const file_accounts_proto_rawDesc = "" +
	"\n" +
	"\x0eaccounts.proto\"\xe3\x03\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\r \x01(\tR\x04slug\x12'\n" +
	"\x0fcurrent_balance\x18\x03 \x01(\x03R\x0ecurrentBalance\x12+\n" +
	"\x11available_balance\x18\x04 \x01(\x03R\x10availableBalance\x12'\n" +
	"\x0fholding_balance\x18\x05 \x01(\x03R\x0eholdingBalance\x122\n" +
	"\bmetadata\x18\x06 \x03(\v2\x16.Account.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12/\n" +
	"\x11is_system_account\x18\f \x01(\bH\x00R\x0fisSystemAccount\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x14\n" +
	"\x12_is_system_account\"X\n" +
	"\vAccountList\x12$\n" +
	"\baccounts\x18\x01 \x03(\v2\b.AccountR\baccounts\x12#\n" +
	"\x05query\x18\x02 \x01(\v2\r.AccountQueryR\x05query\"\xe1\x02\n" +
	"\fAccountQuery\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x00R\x06status\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tH\x01R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x04 \x01(\tH\x02R\aendDate\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x05 \x01(\tH\x03R\x04type\x88\x01\x01\x12\x1f\n" +
	"\bcurrency\x18\x06 \x01(\tH\x04R\bcurrency\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\a \x01(\tH\x05R\x04name\x88\x01\x01\x12/\n" +
	"\x11is_system_account\x18\b \x01(\bH\x06R\x0fisSystemAccount\x88\x01\x01B\t\n" +
	"\a_statusB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\a\n" +
	"\x05_typeB\v\n" +
	"\t_currencyB\a\n" +
	"\x05_nameB\x14\n" +
	"\x12_is_system_account\"\xb9\x02\n" +
	"\tAccountIn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x124\n" +
	"\bmetadata\x18\x03 \x03(\v2\x18.AccountIn.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12/\n" +
	"\x11is_system_account\x18\a \x01(\bH\x00R\x0fisSystemAccount\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x14\n" +
	"\x12_is_system_account\"Z\n" +
	"\rAccountUpdate\x12$\n" +
	"\aaccount\x18\x01 \x01(\v2\n" +
	".AccountInR\aaccount\x12#\n" +
	"\x05query\x18\x02 \x01(\v2\r.AccountQueryR\x05query\"\x96\x02\n" +
	"\aPosting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x03R\x04rate\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x05 \x01(\tR\rdestinationId\x12 \n" +
	"\x06source\x18\x06 \x01(\v2\b.AccountR\x06source\x12*\n" +
	"\vdestination\x18\a \x01(\v2\b.AccountR\vdestination\x12\x1a\n" +
	"\bcommited\x18\b \x01(\bR\bcommited\x12!\n" +
	"\ftransfer_ref\x18\t \x01(\tR\vtransferRef\"0\n" +
	"\bTransfer\x12$\n" +
	"\bpostings\x18\x01 \x03(\v2\b.PostingR\bpostings\"D\n" +
	"\x10TransferResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1f\n" +
	"\vTransferRef\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"<\n" +
	"\x12BulkCreateAccounts\x12&\n" +
	"\baccounts\x18\x01 \x03(\v2\n" +
	".AccountInR\baccounts2\xe5\x03\n" +
	"\x0eAccountService\x12*\n" +
	"\vGetAccounts\x12\r.AccountQuery\x1a\f.AccountList\x12 \n" +
	"\n" +
	"GetAccount\x12\b.Account\x1a\b.Account\x12%\n" +
	"\rCreateAccount\x12\n" +
	".AccountIn\x1a\b.Account\x122\n" +
	"\x11BulkCreateAccount\x12\x13.BulkCreateAccounts\x1a\b.Account\x12-\n" +
	"\rUpdateAccount\x12\x0e.AccountUpdate\x1a\f.AccountList\x12,\n" +
	"\rDeleteAccount\x12\r.AccountQuery\x1a\f.AccountList\x121\n" +
	"\x11TransferAndCommit\x12\t.Transfer\x1a\x11.TransferResponse\x125\n" +
	"\x15TransferWithoutCommit\x12\t.Transfer\x1a\x11.TransferResponse\x120\n" +
	"\rTranferCommit\x12\f.TransferRef\x1a\x11.TransferResponse\x121\n" +
	"\x0eTransferCancel\x12\f.TransferRef\x1a\x11.TransferResponseB\x1eZ\x1cgithub.com/kvbo/protobufs;pbb\x06proto3"

var (
	file_accounts_proto_rawDescOnce sync.Once
	file_accounts_proto_rawDescData []byte
)

func file_accounts_proto_rawDescGZIP() []byte {
	file_accounts_proto_rawDescOnce.Do(func() {
		file_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)))
	})
	return file_accounts_proto_rawDescData
}

var file_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_accounts_proto_goTypes = []any{
	(*Account)(nil),            // 0: Account
	(*AccountList)(nil),        // 1: AccountList
	(*AccountQuery)(nil),       // 2: AccountQuery
	(*AccountIn)(nil),          // 3: AccountIn
	(*AccountUpdate)(nil),      // 4: AccountUpdate
	(*Posting)(nil),            // 5: Posting
	(*Transfer)(nil),           // 6: Transfer
	(*TransferResponse)(nil),   // 7: TransferResponse
	(*TransferRef)(nil),        // 8: TransferRef
	(*BulkCreateAccounts)(nil), // 9: BulkCreateAccounts
	nil,                        // 10: Account.MetadataEntry
	nil,                        // 11: AccountIn.MetadataEntry
}
var file_accounts_proto_depIdxs = []int32{
	10, // 0: Account.metadata:type_name -> Account.MetadataEntry
	0,  // 1: AccountList.accounts:type_name -> Account
	2,  // 2: AccountList.query:type_name -> AccountQuery
	11, // 3: AccountIn.metadata:type_name -> AccountIn.MetadataEntry
	3,  // 4: AccountUpdate.account:type_name -> AccountIn
	2,  // 5: AccountUpdate.query:type_name -> AccountQuery
	0,  // 6: Posting.source:type_name -> Account
	0,  // 7: Posting.destination:type_name -> Account
	5,  // 8: Transfer.postings:type_name -> Posting
	3,  // 9: BulkCreateAccounts.accounts:type_name -> AccountIn
	2,  // 10: AccountService.GetAccounts:input_type -> AccountQuery
	0,  // 11: AccountService.GetAccount:input_type -> Account
	3,  // 12: AccountService.CreateAccount:input_type -> AccountIn
	9,  // 13: AccountService.BulkCreateAccount:input_type -> BulkCreateAccounts
	4,  // 14: AccountService.UpdateAccount:input_type -> AccountUpdate
	2,  // 15: AccountService.DeleteAccount:input_type -> AccountQuery
	6,  // 16: AccountService.TransferAndCommit:input_type -> Transfer
	6,  // 17: AccountService.TransferWithoutCommit:input_type -> Transfer
	8,  // 18: AccountService.TranferCommit:input_type -> TransferRef
	8,  // 19: AccountService.TransferCancel:input_type -> TransferRef
	1,  // 20: AccountService.GetAccounts:output_type -> AccountList
	0,  // 21: AccountService.GetAccount:output_type -> Account
	0,  // 22: AccountService.CreateAccount:output_type -> Account
	0,  // 23: AccountService.BulkCreateAccount:output_type -> Account
	1,  // 24: AccountService.UpdateAccount:output_type -> AccountList
	1,  // 25: AccountService.DeleteAccount:output_type -> AccountList
	7,  // 26: AccountService.TransferAndCommit:output_type -> TransferResponse
	7,  // 27: AccountService.TransferWithoutCommit:output_type -> TransferResponse
	7,  // 28: AccountService.TranferCommit:output_type -> TransferResponse
	7,  // 29: AccountService.TransferCancel:output_type -> TransferResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_accounts_proto_init() }
func file_accounts_proto_init() {
	if File_accounts_proto != nil {
		return
	}
	file_accounts_proto_msgTypes[0].OneofWrappers = []any{}
	file_accounts_proto_msgTypes[2].OneofWrappers = []any{}
	file_accounts_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounts_proto_goTypes,
		DependencyIndexes: file_accounts_proto_depIdxs,
		MessageInfos:      file_accounts_proto_msgTypes,
	}.Build()
	File_accounts_proto = out.File
	file_accounts_proto_goTypes = nil
	file_accounts_proto_depIdxs = nil
}
