// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailPassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailPassword) Reset() {
	*x = EmailPassword{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailPassword) ProtoMessage() {}

func (x *EmailPassword) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailPassword.ProtoReflect.Descriptor instead.
func (*EmailPassword) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *EmailPassword) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailPassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EmailPhonePassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailPhonePassword) Reset() {
	*x = EmailPhonePassword{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailPhonePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailPhonePassword) ProtoMessage() {}

func (x *EmailPhonePassword) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailPhonePassword.ProtoReflect.Descriptor instead.
func (*EmailPhonePassword) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *EmailPhonePassword) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailPhonePassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EmailPhonePassword) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *EmailPhonePassword) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type PhonePassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	CountryCode   string                 `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhonePassword) Reset() {
	*x = PhonePassword{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhonePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhonePassword) ProtoMessage() {}

func (x *PhonePassword) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhonePassword.ProtoReflect.Descriptor instead.
func (*PhonePassword) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *PhonePassword) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhonePassword) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *PhonePassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PhoneOnly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	CountryCode   string                 `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneOnly) Reset() {
	*x = PhoneOnly{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneOnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneOnly) ProtoMessage() {}

func (x *PhoneOnly) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneOnly.ProtoReflect.Descriptor instead.
func (*PhoneOnly) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *PhoneOnly) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhoneOnly) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type EmailOnly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailOnly) Reset() {
	*x = EmailOnly{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailOnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailOnly) ProtoMessage() {}

func (x *EmailOnly) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailOnly.ProtoReflect.Descriptor instead.
func (*EmailOnly) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *EmailOnly) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,12,opt,name=id,proto3,oneof" json:"id,omitempty"`
	FirstName     *string                `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Username      *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Email         *string                `protobuf:"bytes,13,opt,name=email,proto3,oneof" json:"email,omitempty"`
	AppId         *string                `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	TenantId      *string                `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	EmailId       *string                `protobuf:"bytes,6,opt,name=email_id,json=emailId,proto3,oneof" json:"email_id,omitempty"`
	Phone         *string                `protobuf:"bytes,7,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	CountryCode   *string                `protobuf:"bytes,8,opt,name=country_code,json=countryCode,proto3,oneof" json:"country_code,omitempty"`
	Verified      *bool                  `protobuf:"varint,9,opt,name=verified,proto3,oneof" json:"verified,omitempty"`
	Status        *string                `protobuf:"bytes,10,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Avatar        *string                `protobuf:"bytes,11,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *User) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *User) GetEmailId() string {
	if x != nil && x.EmailId != nil {
		return *x.EmailId
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *User) GetCountryCode() string {
	if x != nil && x.CountryCode != nil {
		return *x.CountryCode
	}
	return ""
}

func (x *User) GetVerified() bool {
	if x != nil && x.Verified != nil {
		return *x.Verified
	}
	return false
}

func (x *User) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

type AuthorizedUser struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken          string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessToken           string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	User                  *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	AccessTokenExpiresAt  int64                  `protobuf:"varint,4,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt int64                  `protobuf:"varint,5,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AuthorizedUser) Reset() {
	*x = AuthorizedUser{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedUser) ProtoMessage() {}

func (x *AuthorizedUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedUser.ProtoReflect.Descriptor instead.
func (*AuthorizedUser) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizedUser) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthorizedUser) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthorizedUser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthorizedUser) GetAccessTokenExpiresAt() int64 {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return 0
}

func (x *AuthorizedUser) GetRefreshTokenExpiresAt() int64 {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return 0
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Valid         bool                         `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Decoded       *VerifyTokenResponse_Decoded `protobuf:"bytes,2,opt,name=decoded,proto3" json:"decoded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetDecoded() *VerifyTokenResponse_Decoded {
	if x != nil {
		return x.Decoded
	}
	return nil
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublickeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublickeyRequest) Reset() {
	*x = PublickeyRequest{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublickeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublickeyRequest) ProtoMessage() {}

func (x *PublickeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublickeyRequest.ProtoReflect.Descriptor instead.
func (*PublickeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

type PublickeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublickeyResponse) Reset() {
	*x = PublickeyResponse{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublickeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublickeyResponse) ProtoMessage() {}

func (x *PublickeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublickeyResponse.ProtoReflect.Descriptor instead.
func (*PublickeyResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *PublickeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *AssignRoleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssignRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyTokenResponse_Decoded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	CountryCode   string                 `protobuf:"bytes,6,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	AppId         string                 `protobuf:"bytes,7,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	TenantId      *string                `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse_Decoded) Reset() {
	*x = VerifyTokenResponse_Decoded{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse_Decoded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse_Decoded) ProtoMessage() {}

func (x *VerifyTokenResponse_Decoded) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse_Decoded.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse_Decoded) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8, 0}
}

func (x *VerifyTokenResponse_Decoded) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyTokenResponse_Decoded) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *VerifyTokenResponse_Decoded) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *VerifyTokenResponse_Decoded) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyTokenResponse_Decoded) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifyTokenResponse_Decoded) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *VerifyTokenResponse_Decoded) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *VerifyTokenResponse_Decoded) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\"A\n" +
	"\rEmailPassword\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x7f\n" +
	"\x12EmailPhonePassword\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"d\n" +
	"\rPhonePassword\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"D\n" +
	"\tPhoneOnly\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\"!\n" +
	"\tEmailOnly\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xb8\x04\n" +
	"\x04User\x12\x13\n" +
	"\x02id\x18\f \x01(\tH\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tH\x02R\blastName\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x03R\busername\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\r \x01(\tH\x04R\x05email\x88\x01\x01\x12\x1a\n" +
	"\x06app_id\x18\x04 \x01(\tH\x05R\x05appId\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x05 \x01(\tH\x06R\btenantId\x88\x01\x01\x12\x1e\n" +
	"\bemail_id\x18\x06 \x01(\tH\aR\aemailId\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\a \x01(\tH\bR\x05phone\x88\x01\x01\x12&\n" +
	"\fcountry_code\x18\b \x01(\tH\tR\vcountryCode\x88\x01\x01\x12\x1f\n" +
	"\bverified\x18\t \x01(\bH\n" +
	"R\bverified\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\n" +
	" \x01(\tH\vR\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\v \x01(\tH\fR\x06avatar\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\v\n" +
	"\t_usernameB\b\n" +
	"\x06_emailB\t\n" +
	"\a_app_idB\f\n" +
	"\n" +
	"_tenant_idB\v\n" +
	"\t_email_idB\b\n" +
	"\x06_phoneB\x0f\n" +
	"\r_country_codeB\v\n" +
	"\t_verifiedB\t\n" +
	"\a_statusB\t\n" +
	"\a_avatar\"\xe3\x01\n" +
	"\x0eAuthorizedUser\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x19\n" +
	"\x04user\x18\x03 \x01(\v2\x05.UserR\x04user\x125\n" +
	"\x17access_token_expires_at\x18\x04 \x01(\x03R\x14accessTokenExpiresAt\x127\n" +
	"\x18refresh_token_expires_at\x18\x05 \x01(\x03R\x15refreshTokenExpiresAt\"7\n" +
	"\x12VerifyTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xd1\x02\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x126\n" +
	"\adecoded\x18\x02 \x01(\v2\x1c.VerifyTokenResponse.DecodedR\adecoded\x1a\xeb\x01\n" +
	"\aDecoded\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12!\n" +
	"\fcountry_code\x18\x06 \x01(\tR\vcountryCode\x12\x15\n" +
	"\x06app_id\x18\a \x01(\tR\x05appId\x12 \n" +
	"\ttenant_id\x18\b \x01(\tH\x00R\btenantId\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_id\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10PublickeyRequest\"2\n" +
	"\x11PublickeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"@\n" +
	"\x11AssignRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"F\n" +
	"\x12AssignRoleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd3\x06\n" +
	"\vAuthService\x12.\n" +
	"\x0fSigninWithEmail\x12\n" +
	".EmailOnly\x1a\x0f.AuthorizedUser\x12:\n" +
	"\x17SigninWithEmailPassword\x12\x0e.EmailPassword\x1a\x0f.AuthorizedUser\x12D\n" +
	"\x1cSigninWithEmailPhonePassword\x12\x13.EmailPhonePassword\x1a\x0f.AuthorizedUser\x12.\n" +
	"\x0fSigninWithPhone\x12\n" +
	".PhoneOnly\x1a\x0f.AuthorizedUser\x12:\n" +
	"\x17SigninWithPhonePassword\x12\x0e.PhonePassword\x1a\x0f.AuthorizedUser\x12.\n" +
	"\x0fSignupWithEmail\x12\n" +
	".EmailOnly\x1a\x0f.AuthorizedUser\x12:\n" +
	"\x17SignupWithEmailPassword\x12\x0e.EmailPassword\x1a\x0f.AuthorizedUser\x12D\n" +
	"\x1cSignupWithEmailPhonePassword\x12\x13.EmailPhonePassword\x1a\x0f.AuthorizedUser\x12.\n" +
	"\x0fSignupWithPhone\x12\n" +
	".PhoneOnly\x1a\x0f.AuthorizedUser\x12:\n" +
	"\x17SignupWithPhonePassword\x12\x0e.PhonePassword\x1a\x0f.AuthorizedUser\x128\n" +
	"\vVerifyToken\x12\x13.VerifyTokenRequest\x1a\x14.VerifyTokenResponse\x125\n" +
	"\n" +
	"AssignRole\x12\x12.AssignRoleRequest\x1a\x13.AssignRoleResponse\x125\n" +
	"\fRefreshToken\x12\x14.RefreshTokenRequest\x1a\x0f.AuthorizedUser\x12)\n" +
	"\x06Logout\x12\x0e.LogoutRequest\x1a\x0f.LogoutResponse\x125\n" +
	"\fGetPublicKey\x12\x11.PublickeyRequest\x1a\x12.PublickeyResponseB\x1eZ\x1cgithub.com/kvbo/protobufs;pbb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_auth_proto_goTypes = []any{
	(*EmailPassword)(nil),               // 0: EmailPassword
	(*EmailPhonePassword)(nil),          // 1: EmailPhonePassword
	(*PhonePassword)(nil),               // 2: PhonePassword
	(*PhoneOnly)(nil),                   // 3: PhoneOnly
	(*EmailOnly)(nil),                   // 4: EmailOnly
	(*User)(nil),                        // 5: User
	(*AuthorizedUser)(nil),              // 6: AuthorizedUser
	(*VerifyTokenRequest)(nil),          // 7: VerifyTokenRequest
	(*VerifyTokenResponse)(nil),         // 8: VerifyTokenResponse
	(*RefreshTokenRequest)(nil),         // 9: RefreshTokenRequest
	(*LogoutRequest)(nil),               // 10: LogoutRequest
	(*LogoutResponse)(nil),              // 11: LogoutResponse
	(*PublickeyRequest)(nil),            // 12: PublickeyRequest
	(*PublickeyResponse)(nil),           // 13: PublickeyResponse
	(*AssignRoleRequest)(nil),           // 14: AssignRoleRequest
	(*AssignRoleResponse)(nil),          // 15: AssignRoleResponse
	(*VerifyTokenResponse_Decoded)(nil), // 16: VerifyTokenResponse.Decoded
}
var file_auth_proto_depIdxs = []int32{
	5,  // 0: AuthorizedUser.user:type_name -> User
	16, // 1: VerifyTokenResponse.decoded:type_name -> VerifyTokenResponse.Decoded
	4,  // 2: AuthService.SigninWithEmail:input_type -> EmailOnly
	0,  // 3: AuthService.SigninWithEmailPassword:input_type -> EmailPassword
	1,  // 4: AuthService.SigninWithEmailPhonePassword:input_type -> EmailPhonePassword
	3,  // 5: AuthService.SigninWithPhone:input_type -> PhoneOnly
	2,  // 6: AuthService.SigninWithPhonePassword:input_type -> PhonePassword
	4,  // 7: AuthService.SignupWithEmail:input_type -> EmailOnly
	0,  // 8: AuthService.SignupWithEmailPassword:input_type -> EmailPassword
	1,  // 9: AuthService.SignupWithEmailPhonePassword:input_type -> EmailPhonePassword
	3,  // 10: AuthService.SignupWithPhone:input_type -> PhoneOnly
	2,  // 11: AuthService.SignupWithPhonePassword:input_type -> PhonePassword
	7,  // 12: AuthService.VerifyToken:input_type -> VerifyTokenRequest
	14, // 13: AuthService.AssignRole:input_type -> AssignRoleRequest
	9,  // 14: AuthService.RefreshToken:input_type -> RefreshTokenRequest
	10, // 15: AuthService.Logout:input_type -> LogoutRequest
	12, // 16: AuthService.GetPublicKey:input_type -> PublickeyRequest
	6,  // 17: AuthService.SigninWithEmail:output_type -> AuthorizedUser
	6,  // 18: AuthService.SigninWithEmailPassword:output_type -> AuthorizedUser
	6,  // 19: AuthService.SigninWithEmailPhonePassword:output_type -> AuthorizedUser
	6,  // 20: AuthService.SigninWithPhone:output_type -> AuthorizedUser
	6,  // 21: AuthService.SigninWithPhonePassword:output_type -> AuthorizedUser
	6,  // 22: AuthService.SignupWithEmail:output_type -> AuthorizedUser
	6,  // 23: AuthService.SignupWithEmailPassword:output_type -> AuthorizedUser
	6,  // 24: AuthService.SignupWithEmailPhonePassword:output_type -> AuthorizedUser
	6,  // 25: AuthService.SignupWithPhone:output_type -> AuthorizedUser
	6,  // 26: AuthService.SignupWithPhonePassword:output_type -> AuthorizedUser
	8,  // 27: AuthService.VerifyToken:output_type -> VerifyTokenResponse
	15, // 28: AuthService.AssignRole:output_type -> AssignRoleResponse
	6,  // 29: AuthService.RefreshToken:output_type -> AuthorizedUser
	11, // 30: AuthService.Logout:output_type -> LogoutResponse
	13, // 31: AuthService.GetPublicKey:output_type -> PublickeyResponse
	17, // [17:32] is the sub-list for method output_type
	2,  // [2:17] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_auth_proto_msgTypes[5].OneofWrappers = []any{}
	file_auth_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
