// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: charges.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Breakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Min           *int64                 `protobuf:"varint,2,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *int64                 `protobuf:"varint,3,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Breakdown) Reset() {
	*x = Breakdown{}
	mi := &file_charges_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Breakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Breakdown) ProtoMessage() {}

func (x *Breakdown) ProtoReflect() protoreflect.Message {
	mi := &file_charges_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Breakdown.ProtoReflect.Descriptor instead.
func (*Breakdown) Descriptor() ([]byte, []int) {
	return file_charges_proto_rawDescGZIP(), []int{0}
}

func (x *Breakdown) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Breakdown) GetMin() int64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *Breakdown) GetMax() int64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

// FEE STRUCT
type Fee struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Reversible  *bool                  `protobuf:"varint,4,opt,name=reversible,proto3,oneof" json:"reversible,omitempty"`
	Type        string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                      // previously string, now enum
	FeeType     string                 `protobuf:"bytes,6,opt,name=fee_type,json=feeType,proto3" json:"fee_type,omitempty"` // previously string, now enum
	Breakdown   []*Breakdown           `protobuf:"bytes,7,rep,name=breakdown,proto3" json:"breakdown,omitempty"`
	// for a cost..whose paying
	SourceAccountRef *string `protobuf:"bytes,8,opt,name=source_account_ref,json=sourceAccountRef,proto3,oneof" json:"source_account_ref,omitempty"`
	DestinationAccountRef *string  `protobuf:"bytes,9,opt,name=destination_account_ref,json=destinationAccountRef,proto3,oneof" json:"destination_account_ref,omitempty"`
	Source                *string  `protobuf:"bytes,10,opt,name=source,proto3,oneof" json:"source,omitempty"`
	ServiceIds            []string `protobuf:"bytes,11,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	CreatedAt             *string  `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_charges_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_charges_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_charges_proto_rawDescGZIP(), []int{1}
}

func (x *Fee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Fee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fee) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Fee) GetReversible() bool {
	if x != nil && x.Reversible != nil {
		return *x.Reversible
	}
	return false
}

func (x *Fee) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Fee) GetFeeType() string {
	if x != nil {
		return x.FeeType
	}
	return ""
}

func (x *Fee) GetBreakdown() []*Breakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *Fee) GetSourceAccountRef() string {
	if x != nil && x.SourceAccountRef != nil {
		return *x.SourceAccountRef
	}
	return ""
}

func (x *Fee) GetDestinationAccountRef() string {
	if x != nil && x.DestinationAccountRef != nil {
		return *x.DestinationAccountRef
	}
	return ""
}

func (x *Fee) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Fee) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

func (x *Fee) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

// PAGINATED FEE LIST
type FeeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fee           []*Fee                 `protobuf:"bytes,1,rep,name=fee,proto3" json:"fee,omitempty"`
	Query         *FeeQuery              `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeList) Reset() {
	*x = FeeList{}
	mi := &file_charges_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeList) ProtoMessage() {}

func (x *FeeList) ProtoReflect() protoreflect.Message {
	mi := &file_charges_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeList.ProtoReflect.Descriptor instead.
func (*FeeList) Descriptor() ([]byte, []int) {
	return file_charges_proto_rawDescGZIP(), []int{2}
}

func (x *FeeList) GetFee() []*Fee {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *FeeList) GetQuery() *FeeQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// FEE FILTERING QUERY
type FeeQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeQuery) Reset() {
	*x = FeeQuery{}
	mi := &file_charges_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeQuery) ProtoMessage() {}

func (x *FeeQuery) ProtoReflect() protoreflect.Message {
	mi := &file_charges_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeQuery.ProtoReflect.Descriptor instead.
func (*FeeQuery) Descriptor() ([]byte, []int) {
	return file_charges_proto_rawDescGZIP(), []int{3}
}

func (x *FeeQuery) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *FeeQuery) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_charges_proto protoreflect.FileDescriptor

const file_charges_proto_rawDesc = "" +
	"\n" +
	"\rcharges.proto\"_\n" +
	"\tBreakdown\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x15\n" +
	"\x03min\x18\x02 \x01(\x03H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x03 \x01(\x03H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"\xf7\x03\n" +
	"\x03Fee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\n" +
	"reversible\x18\x04 \x01(\bH\x00R\n" +
	"reversible\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x19\n" +
	"\bfee_type\x18\x06 \x01(\tR\afeeType\x12(\n" +
	"\tbreakdown\x18\a \x03(\v2\n" +
	".BreakdownR\tbreakdown\x121\n" +
	"\x12source_account_ref\x18\b \x01(\tH\x01R\x10sourceAccountRef\x88\x01\x01\x12;\n" +
	"\x17destination_account_ref\x18\t \x01(\tH\x02R\x15destinationAccountRef\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\n" +
	" \x01(\tH\x03R\x06source\x88\x01\x01\x12\x1f\n" +
	"\vservice_ids\x18\v \x03(\tR\n" +
	"serviceIds\x12\"\n" +
	"\n" +
	"created_at\x18\f \x01(\tH\x04R\tcreatedAt\x88\x01\x01B\r\n" +
	"\v_reversibleB\x15\n" +
	"\x13_source_account_refB\x1a\n" +
	"\x18_destination_account_refB\t\n" +
	"\a_sourceB\r\n" +
	"\v_created_at\"B\n" +
	"\aFeeList\x12\x16\n" +
	"\x03fee\x18\x01 \x03(\v2\x04.FeeR\x03fee\x12\x1f\n" +
	"\x05query\x18\x02 \x01(\v2\t.FeeQueryR\x05query\"9\n" +
	"\bFeeQuery\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids2\x9d\x01\n" +
	"\n" +
	"FeeManager\x12\x17\n" +
	"\tCreateFee\x12\x04.Fee\x1a\x04.Fee\x12\x1f\n" +
	"\tUpdateFee\x12\b.FeeList\x1a\b.FeeList\x12\x14\n" +
	"\x06GetFee\x12\x04.Fee\x1a\x04.Fee\x12\x1d\n" +
	"\aGetFees\x12\b.FeeList\x1a\b.FeeList\x12 \n" +
	"\tDeleteFee\x12\t.FeeQuery\x1a\b.FeeListB\x1eZ\x1cgithub.com/kvbo/protobufs;pbb\x06proto3"

var (
	file_charges_proto_rawDescOnce sync.Once
	file_charges_proto_rawDescData []byte
)

func file_charges_proto_rawDescGZIP() []byte {
	file_charges_proto_rawDescOnce.Do(func() {
		file_charges_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_charges_proto_rawDesc), len(file_charges_proto_rawDesc)))
	})
	return file_charges_proto_rawDescData
}

var file_charges_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_charges_proto_goTypes = []any{
	(*Breakdown)(nil), // 0: Breakdown
	(*Fee)(nil),       // 1: Fee
	(*FeeList)(nil),   // 2: FeeList
	(*FeeQuery)(nil),  // 3: FeeQuery
}
var file_charges_proto_depIdxs = []int32{
	0, // 0: Fee.breakdown:type_name -> Breakdown
	1, // 1: FeeList.fee:type_name -> Fee
	3, // 2: FeeList.query:type_name -> FeeQuery
	1, // 3: FeeManager.CreateFee:input_type -> Fee
	2, // 4: FeeManager.UpdateFee:input_type -> FeeList
	1, // 5: FeeManager.GetFee:input_type -> Fee
	2, // 6: FeeManager.GetFees:input_type -> FeeList
	3, // 7: FeeManager.DeleteFee:input_type -> FeeQuery
	1, // 8: FeeManager.CreateFee:output_type -> Fee
	2, // 9: FeeManager.UpdateFee:output_type -> FeeList
	1, // 10: FeeManager.GetFee:output_type -> Fee
	2, // 11: FeeManager.GetFees:output_type -> FeeList
	2, // 12: FeeManager.DeleteFee:output_type -> FeeList
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_charges_proto_init() }
func file_charges_proto_init() {
	if File_charges_proto != nil {
		return
	}
	file_charges_proto_msgTypes[0].OneofWrappers = []any{}
	file_charges_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_charges_proto_rawDesc), len(file_charges_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_charges_proto_goTypes,
		DependencyIndexes: file_charges_proto_depIdxs,
		MessageInfos:      file_charges_proto_msgTypes,
	}.Build()
	File_charges_proto = out.File
	file_charges_proto_goTypes = nil
	file_charges_proto_depIdxs = nil
}
