// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: kyc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entity type enum
type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED EntityType = 0
	EntityType_ENTITY_TYPE_BUSINESS    EntityType = 1
	EntityType_ENTITY_TYPE_INDIVIDUAL  EntityType = 2
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "ENTITY_TYPE_BUSINESS",
		2: "ENTITY_TYPE_INDIVIDUAL",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED": 0,
		"ENTITY_TYPE_BUSINESS":    1,
		"ENTITY_TYPE_INDIVIDUAL":  2,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_kyc_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_kyc_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{0}
}

// Address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apartment     *string                `protobuf:"bytes,1,opt,name=apartment,proto3,oneof" json:"apartment,omitempty"`
	Line1         *string                `protobuf:"bytes,2,opt,name=line1,proto3,oneof" json:"line1,omitempty"`
	Line2         *string                `protobuf:"bytes,3,opt,name=line2,proto3,oneof" json:"line2,omitempty"`
	Country       *string                `protobuf:"bytes,4,opt,name=country,proto3,oneof" json:"country,omitempty"`
	PostalCode    *string                `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"`
	City          *string                `protobuf:"bytes,6,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string                `protobuf:"bytes,7,opt,name=state,proto3,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_kyc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetApartment() string {
	if x != nil && x.Apartment != nil {
		return *x.Apartment
	}
	return ""
}

func (x *Address) GetLine1() string {
	if x != nil && x.Line1 != nil {
		return *x.Line1
	}
	return ""
}

func (x *Address) GetLine2() string {
	if x != nil && x.Line2 != nil {
		return *x.Line2
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

// Contact
type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"` // email, phone, website
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_kyc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Contact) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// Document
type Document struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	IssuingCountry *string                `protobuf:"bytes,2,opt,name=issuing_country,json=issuingCountry,proto3,oneof" json:"issuing_country,omitempty"`
	Number         *string                `protobuf:"bytes,3,opt,name=number,proto3,oneof" json:"number,omitempty"`
	ExpiryDate     *string                `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate,proto3,oneof" json:"expiry_date,omitempty"`
	IssueDate      *string                `protobuf:"bytes,5,opt,name=issue_date,json=issueDate,proto3,oneof" json:"issue_date,omitempty"`
	Scans          []string               `protobuf:"bytes,6,rep,name=scans,proto3" json:"scans,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_kyc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{2}
}

func (x *Document) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Document) GetIssuingCountry() string {
	if x != nil && x.IssuingCountry != nil {
		return *x.IssuingCountry
	}
	return ""
}

func (x *Document) GetNumber() string {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return ""
}

func (x *Document) GetExpiryDate() string {
	if x != nil && x.ExpiryDate != nil {
		return *x.ExpiryDate
	}
	return ""
}

func (x *Document) GetIssueDate() string {
	if x != nil && x.IssueDate != nil {
		return *x.IssueDate
	}
	return ""
}

func (x *Document) GetScans() []string {
	if x != nil {
		return x.Scans
	}
	return nil
}

// Person
type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     *string                `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	OtherName     *string                `protobuf:"bytes,3,opt,name=other_name,json=otherName,proto3,oneof" json:"other_name,omitempty"`
	Dob           *string                `protobuf:"bytes,4,opt,name=dob,proto3,oneof" json:"dob,omitempty"`
	Nationality   *string                `protobuf:"bytes,5,opt,name=nationality,proto3,oneof" json:"nationality,omitempty"`
	Gender        *string                `protobuf:"bytes,7,opt,name=gender,proto3,oneof" json:"gender,omitempty"` // male, female, other
	Contacts      []*Contact             `protobuf:"bytes,8,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_kyc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{3}
}

func (x *Person) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *Person) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *Person) GetOtherName() string {
	if x != nil && x.OtherName != nil {
		return *x.OtherName
	}
	return ""
}

func (x *Person) GetDob() string {
	if x != nil && x.Dob != nil {
		return *x.Dob
	}
	return ""
}

func (x *Person) GetNationality() string {
	if x != nil && x.Nationality != nil {
		return *x.Nationality
	}
	return ""
}

func (x *Person) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *Person) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

// Business
type Business struct {
	state                 protoimpl.MessageState      `protogen:"open.v1"`
	Name                  *string                     `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Industry              *string                     `protobuf:"bytes,2,opt,name=industry,proto3,oneof" json:"industry,omitempty"`
	CountryOfRegistration *string                     `protobuf:"bytes,3,opt,name=country_of_registration,json=countryOfRegistration,proto3,oneof" json:"country_of_registration,omitempty"`
	IncorporationDate     *string                     `protobuf:"bytes,4,opt,name=incorporation_date,json=incorporationDate,proto3,oneof" json:"incorporation_date,omitempty"`
	RegistrationNumber    *string                     `protobuf:"bytes,5,opt,name=registration_number,json=registrationNumber,proto3,oneof" json:"registration_number,omitempty"`
	Contacts              []*Contact                  `protobuf:"bytes,6,rep,name=contacts,proto3" json:"contacts,omitempty"`
	BeneficialOwners      []*Business_BeneficialOwner `protobuf:"bytes,7,rep,name=beneficial_owners,json=beneficialOwners,proto3" json:"beneficial_owners,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Business) Reset() {
	*x = Business{}
	mi := &file_kyc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Business) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Business) ProtoMessage() {}

func (x *Business) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Business.ProtoReflect.Descriptor instead.
func (*Business) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{4}
}

func (x *Business) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Business) GetIndustry() string {
	if x != nil && x.Industry != nil {
		return *x.Industry
	}
	return ""
}

func (x *Business) GetCountryOfRegistration() string {
	if x != nil && x.CountryOfRegistration != nil {
		return *x.CountryOfRegistration
	}
	return ""
}

func (x *Business) GetIncorporationDate() string {
	if x != nil && x.IncorporationDate != nil {
		return *x.IncorporationDate
	}
	return ""
}

func (x *Business) GetRegistrationNumber() string {
	if x != nil && x.RegistrationNumber != nil {
		return *x.RegistrationNumber
	}
	return ""
}

func (x *Business) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *Business) GetBeneficialOwners() []*Business_BeneficialOwner {
	if x != nil {
		return x.BeneficialOwners
	}
	return nil
}

// Entity wrapper
type Entity struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	ExternalReference  *string                `protobuf:"bytes,2,opt,name=external_reference,json=externalReference,proto3,oneof" json:"external_reference,omitempty"`
	Name               *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Type               *EntityType            `protobuf:"varint,4,opt,name=type,proto3,enum=EntityType,oneof" json:"type,omitempty"`
	Email              *string                `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	CountryCode        *string                `protobuf:"bytes,6,opt,name=country_code,json=countryCode,proto3,oneof" json:"country_code,omitempty"`
	Phone              *string                `protobuf:"bytes,7,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Address            *Address               `protobuf:"bytes,8,opt,name=address,proto3,oneof" json:"address,omitempty"`
	VerificationStatus *string                `protobuf:"bytes,9,opt,name=verification_status,json=verificationStatus,proto3,oneof" json:"verification_status,omitempty"`
	VerificationDate   *string                `protobuf:"bytes,10,opt,name=verification_date,json=verificationDate,proto3,oneof" json:"verification_date,omitempty"`
	VerifiedBy         *string                `protobuf:"bytes,11,opt,name=verified_by,json=verifiedBy,proto3,oneof" json:"verified_by,omitempty"`
	Documents          []*Document            `protobuf:"bytes,12,rep,name=documents,proto3" json:"documents,omitempty"`
	Tpin               *string                `protobuf:"bytes,13,opt,name=tpin,proto3,oneof" json:"tpin,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*Entity_Person
	//	*Entity_Business
	Details       isEntity_Details `protobuf_oneof:"details"`
	CreatedAt     *string          `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_kyc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{5}
}

func (x *Entity) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Entity) GetExternalReference() string {
	if x != nil && x.ExternalReference != nil {
		return *x.ExternalReference
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Entity) GetType() EntityType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return EntityType_ENTITY_TYPE_UNSPECIFIED
}

func (x *Entity) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Entity) GetCountryCode() string {
	if x != nil && x.CountryCode != nil {
		return *x.CountryCode
	}
	return ""
}

func (x *Entity) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Entity) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Entity) GetVerificationStatus() string {
	if x != nil && x.VerificationStatus != nil {
		return *x.VerificationStatus
	}
	return ""
}

func (x *Entity) GetVerificationDate() string {
	if x != nil && x.VerificationDate != nil {
		return *x.VerificationDate
	}
	return ""
}

func (x *Entity) GetVerifiedBy() string {
	if x != nil && x.VerifiedBy != nil {
		return *x.VerifiedBy
	}
	return ""
}

func (x *Entity) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *Entity) GetTpin() string {
	if x != nil && x.Tpin != nil {
		return *x.Tpin
	}
	return ""
}

func (x *Entity) GetDetails() isEntity_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Entity) GetPerson() *Person {
	if x != nil {
		if x, ok := x.Details.(*Entity_Person); ok {
			return x.Person
		}
	}
	return nil
}

func (x *Entity) GetBusiness() *Business {
	if x != nil {
		if x, ok := x.Details.(*Entity_Business); ok {
			return x.Business
		}
	}
	return nil
}

func (x *Entity) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

type isEntity_Details interface {
	isEntity_Details()
}

type Entity_Person struct {
	Person *Person `protobuf:"bytes,14,opt,name=person,proto3,oneof"`
}

type Entity_Business struct {
	Business *Business `protobuf:"bytes,15,opt,name=business,proto3,oneof"`
}

func (*Entity_Person) isEntity_Details() {}

func (*Entity_Business) isEntity_Details() {}

// Requests / Responses
type CreateEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntityRequest) Reset() {
	*x = CreateEntityRequest{}
	mi := &file_kyc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityRequest) ProtoMessage() {}

func (x *CreateEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntityRequest.ProtoReflect.Descriptor instead.
func (*CreateEntityRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEntityRequest) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type CreateEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntityResponse) Reset() {
	*x = CreateEntityResponse{}
	mi := &file_kyc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityResponse) ProtoMessage() {}

func (x *CreateEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntityResponse.ProtoReflect.Descriptor instead.
func (*CreateEntityResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEntityResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type GetEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterJson    string                 `protobuf:"bytes,1,opt,name=filter_json,json=filterJson,proto3" json:"filter_json,omitempty"` // pass filters as JSON string (flexible)
	Limit         *int64                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitiesRequest) Reset() {
	*x = GetEntitiesRequest{}
	mi := &file_kyc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitiesRequest) ProtoMessage() {}

func (x *GetEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitiesRequest.ProtoReflect.Descriptor instead.
func (*GetEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{8}
}

func (x *GetEntitiesRequest) GetFilterJson() string {
	if x != nil {
		return x.FilterJson
	}
	return ""
}

func (x *GetEntitiesRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetEntitiesRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitiesResponse) Reset() {
	*x = GetEntitiesResponse{}
	mi := &file_kyc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitiesResponse) ProtoMessage() {}

func (x *GetEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitiesResponse.ProtoReflect.Descriptor instead.
func (*GetEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{9}
}

func (x *GetEntitiesResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GetEntityByRefRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExternalReference string                 `protobuf:"bytes,1,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetEntityByRefRequest) Reset() {
	*x = GetEntityByRefRequest{}
	mi := &file_kyc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityByRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityByRefRequest) ProtoMessage() {}

func (x *GetEntityByRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityByRefRequest.ProtoReflect.Descriptor instead.
func (*GetEntityByRefRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{10}
}

func (x *GetEntityByRefRequest) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

type GetEntityByRefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityByRefResponse) Reset() {
	*x = GetEntityByRefResponse{}
	mi := &file_kyc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityByRefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityByRefResponse) ProtoMessage() {}

func (x *GetEntityByRefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityByRefResponse.ProtoReflect.Descriptor instead.
func (*GetEntityByRefResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{11}
}

func (x *GetEntityByRefResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type UpdateEntityByRefRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExternalReference string                 `protobuf:"bytes,1,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	Update            *Entity                `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateEntityByRefRequest) Reset() {
	*x = UpdateEntityByRefRequest{}
	mi := &file_kyc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityByRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityByRefRequest) ProtoMessage() {}

func (x *UpdateEntityByRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityByRefRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntityByRefRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEntityByRefRequest) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

func (x *UpdateEntityByRefRequest) GetUpdate() *Entity {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateEntityByRefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntityByRefResponse) Reset() {
	*x = UpdateEntityByRefResponse{}
	mi := &file_kyc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityByRefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityByRefResponse) ProtoMessage() {}

func (x *UpdateEntityByRefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityByRefResponse.ProtoReflect.Descriptor instead.
func (*UpdateEntityByRefResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateEntityByRefResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type RemoveEntityByRefRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExternalReference string                 `protobuf:"bytes,1,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoveEntityByRefRequest) Reset() {
	*x = RemoveEntityByRefRequest{}
	mi := &file_kyc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEntityByRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEntityByRefRequest) ProtoMessage() {}

func (x *RemoveEntityByRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEntityByRefRequest.ProtoReflect.Descriptor instead.
func (*RemoveEntityByRefRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveEntityByRefRequest) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

type RemoveEntityByRefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEntityByRefResponse) Reset() {
	*x = RemoveEntityByRefResponse{}
	mi := &file_kyc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEntityByRefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEntityByRefResponse) ProtoMessage() {}

func (x *RemoveEntityByRefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEntityByRefResponse.ProtoReflect.Descriptor instead.
func (*RemoveEntityByRefResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveEntityByRefResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdType        string                 `protobuf:"bytes,1,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"` //tping,number,account_number,
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusRequest) Reset() {
	*x = CheckStatusRequest{}
	mi := &file_kyc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusRequest) ProtoMessage() {}

func (x *CheckStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckStatusRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{16}
}

func (x *CheckStatusRequest) GetIdType() string {
	if x != nil {
		return x.IdType
	}
	return ""
}

func (x *CheckStatusRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CheckStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusResponse) Reset() {
	*x = CheckStatusResponse{}
	mi := &file_kyc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusResponse) ProtoMessage() {}

func (x *CheckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckStatusResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{17}
}

func (x *CheckStatusResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *CheckStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Business_BeneficialOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3,oneof" json:"person,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Business_BeneficialOwner) Reset() {
	*x = Business_BeneficialOwner{}
	mi := &file_kyc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Business_BeneficialOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Business_BeneficialOwner) ProtoMessage() {}

func (x *Business_BeneficialOwner) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Business_BeneficialOwner.ProtoReflect.Descriptor instead.
func (*Business_BeneficialOwner) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Business_BeneficialOwner) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *Business_BeneficialOwner) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_kyc_proto protoreflect.FileDescriptor

const file_kyc_proto_rawDesc = "" +
	"\n" +
	"\tkyc.proto\"\xac\x02\n" +
	"\aAddress\x12!\n" +
	"\tapartment\x18\x01 \x01(\tH\x00R\tapartment\x88\x01\x01\x12\x19\n" +
	"\x05line1\x18\x02 \x01(\tH\x01R\x05line1\x88\x01\x01\x12\x19\n" +
	"\x05line2\x18\x03 \x01(\tH\x02R\x05line2\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x04 \x01(\tH\x03R\acountry\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\x05 \x01(\tH\x04R\n" +
	"postalCode\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x06 \x01(\tH\x05R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\a \x01(\tH\x06R\x05state\x88\x01\x01B\f\n" +
	"\n" +
	"_apartmentB\b\n" +
	"\x06_line1B\b\n" +
	"\x06_line2B\n" +
	"\n" +
	"\b_countryB\x0e\n" +
	"\f_postal_codeB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_state\"P\n" +
	"\aContact\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x01R\x05value\x88\x01\x01B\a\n" +
	"\x05_typeB\b\n" +
	"\x06_value\"\x95\x02\n" +
	"\bDocument\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x88\x01\x01\x12,\n" +
	"\x0fissuing_country\x18\x02 \x01(\tH\x01R\x0eissuingCountry\x88\x01\x01\x12\x1b\n" +
	"\x06number\x18\x03 \x01(\tH\x02R\x06number\x88\x01\x01\x12$\n" +
	"\vexpiry_date\x18\x04 \x01(\tH\x03R\n" +
	"expiryDate\x88\x01\x01\x12\"\n" +
	"\n" +
	"issue_date\x18\x05 \x01(\tH\x04R\tissueDate\x88\x01\x01\x12\x14\n" +
	"\x05scans\x18\x06 \x03(\tR\x05scansB\a\n" +
	"\x05_typeB\x12\n" +
	"\x10_issuing_countryB\t\n" +
	"\a_numberB\x0e\n" +
	"\f_expiry_dateB\r\n" +
	"\v_issue_date\"\xc2\x02\n" +
	"\x06Person\x12\"\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tH\x01R\blastName\x88\x01\x01\x12\"\n" +
	"\n" +
	"other_name\x18\x03 \x01(\tH\x02R\totherName\x88\x01\x01\x12\x15\n" +
	"\x03dob\x18\x04 \x01(\tH\x03R\x03dob\x88\x01\x01\x12%\n" +
	"\vnationality\x18\x05 \x01(\tH\x04R\vnationality\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\a \x01(\tH\x05R\x06gender\x88\x01\x01\x12$\n" +
	"\bcontacts\x18\b \x03(\v2\b.ContactR\bcontactsB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\r\n" +
	"\v_other_nameB\x06\n" +
	"\x04_dobB\x0e\n" +
	"\f_nationalityB\t\n" +
	"\a_gender\"\xb3\x04\n" +
	"\bBusiness\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bindustry\x18\x02 \x01(\tH\x01R\bindustry\x88\x01\x01\x12;\n" +
	"\x17country_of_registration\x18\x03 \x01(\tH\x02R\x15countryOfRegistration\x88\x01\x01\x122\n" +
	"\x12incorporation_date\x18\x04 \x01(\tH\x03R\x11incorporationDate\x88\x01\x01\x124\n" +
	"\x13registration_number\x18\x05 \x01(\tH\x04R\x12registrationNumber\x88\x01\x01\x12$\n" +
	"\bcontacts\x18\x06 \x03(\v2\b.ContactR\bcontacts\x12F\n" +
	"\x11beneficial_owners\x18\a \x03(\v2\x19.Business.BeneficialOwnerR\x10beneficialOwners\x1aw\n" +
	"\x0fBeneficialOwner\x12$\n" +
	"\x06person\x18\x01 \x01(\v2\a.PersonH\x00R\x06person\x88\x01\x01\x12'\n" +
	"\aaddress\x18\x02 \x01(\v2\b.AddressH\x01R\aaddress\x88\x01\x01B\t\n" +
	"\a_personB\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_nameB\v\n" +
	"\t_industryB\x1a\n" +
	"\x18_country_of_registrationB\x15\n" +
	"\x13_incorporation_dateB\x16\n" +
	"\x14_registration_number\"\x99\x06\n" +
	"\x06Entity\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x01R\x02id\x88\x01\x01\x122\n" +
	"\x12external_reference\x18\x02 \x01(\tH\x02R\x11externalReference\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x03R\x04name\x88\x01\x01\x12$\n" +
	"\x04type\x18\x04 \x01(\x0e2\v.EntityTypeH\x04R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x05 \x01(\tH\x05R\x05email\x88\x01\x01\x12&\n" +
	"\fcountry_code\x18\x06 \x01(\tH\x06R\vcountryCode\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\a \x01(\tH\aR\x05phone\x88\x01\x01\x12'\n" +
	"\aaddress\x18\b \x01(\v2\b.AddressH\bR\aaddress\x88\x01\x01\x124\n" +
	"\x13verification_status\x18\t \x01(\tH\tR\x12verificationStatus\x88\x01\x01\x120\n" +
	"\x11verification_date\x18\n" +
	" \x01(\tH\n" +
	"R\x10verificationDate\x88\x01\x01\x12$\n" +
	"\vverified_by\x18\v \x01(\tH\vR\n" +
	"verifiedBy\x88\x01\x01\x12'\n" +
	"\tdocuments\x18\f \x03(\v2\t.DocumentR\tdocuments\x12\x17\n" +
	"\x04tpin\x18\r \x01(\tH\fR\x04tpin\x88\x01\x01\x12!\n" +
	"\x06person\x18\x0e \x01(\v2\a.PersonH\x00R\x06person\x12'\n" +
	"\bbusiness\x18\x0f \x01(\v2\t.BusinessH\x00R\bbusiness\x12\"\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tH\rR\tcreatedAt\x88\x01\x01B\t\n" +
	"\adetailsB\x05\n" +
	"\x03_idB\x15\n" +
	"\x13_external_referenceB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_typeB\b\n" +
	"\x06_emailB\x0f\n" +
	"\r_country_codeB\b\n" +
	"\x06_phoneB\n" +
	"\n" +
	"\b_addressB\x16\n" +
	"\x14_verification_statusB\x14\n" +
	"\x12_verification_dateB\x0e\n" +
	"\f_verified_byB\a\n" +
	"\x05_tpinB\r\n" +
	"\v_created_at\"6\n" +
	"\x13CreateEntityRequest\x12\x1f\n" +
	"\x06entity\x18\x01 \x01(\v2\a.EntityR\x06entity\"7\n" +
	"\x14CreateEntityResponse\x12\x1f\n" +
	"\x06entity\x18\x01 \x01(\v2\a.EntityR\x06entity\"\x82\x01\n" +
	"\x12GetEntitiesRequest\x12\x1f\n" +
	"\vfilter_json\x18\x01 \x01(\tR\n" +
	"filterJson\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x03H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x03H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\":\n" +
	"\x13GetEntitiesResponse\x12#\n" +
	"\bentities\x18\x01 \x03(\v2\a.EntityR\bentities\"F\n" +
	"\x15GetEntityByRefRequest\x12-\n" +
	"\x12external_reference\x18\x01 \x01(\tR\x11externalReference\"9\n" +
	"\x16GetEntityByRefResponse\x12\x1f\n" +
	"\x06entity\x18\x01 \x01(\v2\a.EntityR\x06entity\"j\n" +
	"\x18UpdateEntityByRefRequest\x12-\n" +
	"\x12external_reference\x18\x01 \x01(\tR\x11externalReference\x12\x1f\n" +
	"\x06update\x18\x02 \x01(\v2\a.EntityR\x06update\"<\n" +
	"\x19UpdateEntityByRefResponse\x12\x1f\n" +
	"\x06entity\x18\x01 \x01(\v2\a.EntityR\x06entity\"I\n" +
	"\x18RemoveEntityByRefRequest\x12-\n" +
	"\x12external_reference\x18\x01 \x01(\tR\x11externalReference\"5\n" +
	"\x19RemoveEntityByRefResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x12CheckStatusRequest\x12\x17\n" +
	"\aid_type\x18\x01 \x01(\tR\x06idType\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"N\n" +
	"\x13CheckStatusResponse\x12\x1f\n" +
	"\x06entity\x18\x01 \x01(\v2\a.EntityR\x06entity\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status*_\n" +
	"\n" +
	"EntityType\x12\x1b\n" +
	"\x17ENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ENTITY_TYPE_BUSINESS\x10\x01\x12\x1a\n" +
	"\x16ENTITY_TYPE_INDIVIDUAL\x10\x022\x9b\x03\n" +
	"\rEntityService\x12;\n" +
	"\fCreateEntity\x12\x14.CreateEntityRequest\x1a\x15.CreateEntityResponse\x128\n" +
	"\vGetEntities\x12\x13.GetEntitiesRequest\x1a\x14.GetEntitiesResponse\x12A\n" +
	"\x0eGetEntityByRef\x12\x16.GetEntityByRefRequest\x1a\x17.GetEntityByRefResponse\x12J\n" +
	"\x11UpdateEntityByRef\x12\x19.UpdateEntityByRefRequest\x1a\x1a.UpdateEntityByRefResponse\x12J\n" +
	"\x11RemoveEntityByRef\x12\x19.RemoveEntityByRefRequest\x1a\x1a.RemoveEntityByRefResponse\x128\n" +
	"\vCheckStatus\x12\x13.CheckStatusRequest\x1a\x14.CheckStatusResponseB\x1eZ\x1cgithub.com/kvbo/protobufs;pbb\x06proto3"

var (
	file_kyc_proto_rawDescOnce sync.Once
	file_kyc_proto_rawDescData []byte
)

func file_kyc_proto_rawDescGZIP() []byte {
	file_kyc_proto_rawDescOnce.Do(func() {
		file_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kyc_proto_rawDesc), len(file_kyc_proto_rawDesc)))
	})
	return file_kyc_proto_rawDescData
}

var file_kyc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_kyc_proto_goTypes = []any{
	(EntityType)(0),                   // 0: EntityType
	(*Address)(nil),                   // 1: Address
	(*Contact)(nil),                   // 2: Contact
	(*Document)(nil),                  // 3: Document
	(*Person)(nil),                    // 4: Person
	(*Business)(nil),                  // 5: Business
	(*Entity)(nil),                    // 6: Entity
	(*CreateEntityRequest)(nil),       // 7: CreateEntityRequest
	(*CreateEntityResponse)(nil),      // 8: CreateEntityResponse
	(*GetEntitiesRequest)(nil),        // 9: GetEntitiesRequest
	(*GetEntitiesResponse)(nil),       // 10: GetEntitiesResponse
	(*GetEntityByRefRequest)(nil),     // 11: GetEntityByRefRequest
	(*GetEntityByRefResponse)(nil),    // 12: GetEntityByRefResponse
	(*UpdateEntityByRefRequest)(nil),  // 13: UpdateEntityByRefRequest
	(*UpdateEntityByRefResponse)(nil), // 14: UpdateEntityByRefResponse
	(*RemoveEntityByRefRequest)(nil),  // 15: RemoveEntityByRefRequest
	(*RemoveEntityByRefResponse)(nil), // 16: RemoveEntityByRefResponse
	(*CheckStatusRequest)(nil),        // 17: CheckStatusRequest
	(*CheckStatusResponse)(nil),       // 18: CheckStatusResponse
	(*Business_BeneficialOwner)(nil),  // 19: Business.BeneficialOwner
}
var file_kyc_proto_depIdxs = []int32{
	2,  // 0: Person.contacts:type_name -> Contact
	2,  // 1: Business.contacts:type_name -> Contact
	19, // 2: Business.beneficial_owners:type_name -> Business.BeneficialOwner
	0,  // 3: Entity.type:type_name -> EntityType
	1,  // 4: Entity.address:type_name -> Address
	3,  // 5: Entity.documents:type_name -> Document
	4,  // 6: Entity.person:type_name -> Person
	5,  // 7: Entity.business:type_name -> Business
	6,  // 8: CreateEntityRequest.entity:type_name -> Entity
	6,  // 9: CreateEntityResponse.entity:type_name -> Entity
	6,  // 10: GetEntitiesResponse.entities:type_name -> Entity
	6,  // 11: GetEntityByRefResponse.entity:type_name -> Entity
	6,  // 12: UpdateEntityByRefRequest.update:type_name -> Entity
	6,  // 13: UpdateEntityByRefResponse.entity:type_name -> Entity
	6,  // 14: CheckStatusResponse.entity:type_name -> Entity
	4,  // 15: Business.BeneficialOwner.person:type_name -> Person
	1,  // 16: Business.BeneficialOwner.address:type_name -> Address
	7,  // 17: EntityService.CreateEntity:input_type -> CreateEntityRequest
	9,  // 18: EntityService.GetEntities:input_type -> GetEntitiesRequest
	11, // 19: EntityService.GetEntityByRef:input_type -> GetEntityByRefRequest
	13, // 20: EntityService.UpdateEntityByRef:input_type -> UpdateEntityByRefRequest
	15, // 21: EntityService.RemoveEntityByRef:input_type -> RemoveEntityByRefRequest
	17, // 22: EntityService.CheckStatus:input_type -> CheckStatusRequest
	8,  // 23: EntityService.CreateEntity:output_type -> CreateEntityResponse
	10, // 24: EntityService.GetEntities:output_type -> GetEntitiesResponse
	12, // 25: EntityService.GetEntityByRef:output_type -> GetEntityByRefResponse
	14, // 26: EntityService.UpdateEntityByRef:output_type -> UpdateEntityByRefResponse
	16, // 27: EntityService.RemoveEntityByRef:output_type -> RemoveEntityByRefResponse
	18, // 28: EntityService.CheckStatus:output_type -> CheckStatusResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_kyc_proto_init() }
func file_kyc_proto_init() {
	if File_kyc_proto != nil {
		return
	}
	file_kyc_proto_msgTypes[0].OneofWrappers = []any{}
	file_kyc_proto_msgTypes[1].OneofWrappers = []any{}
	file_kyc_proto_msgTypes[2].OneofWrappers = []any{}
	file_kyc_proto_msgTypes[3].OneofWrappers = []any{}
	file_kyc_proto_msgTypes[4].OneofWrappers = []any{}
	file_kyc_proto_msgTypes[5].OneofWrappers = []any{
		(*Entity_Person)(nil),
		(*Entity_Business)(nil),
	}
	file_kyc_proto_msgTypes[8].OneofWrappers = []any{}
	file_kyc_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kyc_proto_rawDesc), len(file_kyc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kyc_proto_goTypes,
		DependencyIndexes: file_kyc_proto_depIdxs,
		EnumInfos:         file_kyc_proto_enumTypes,
		MessageInfos:      file_kyc_proto_msgTypes,
	}.Build()
	File_kyc_proto = out.File
	file_kyc_proto_goTypes = nil
	file_kyc_proto_depIdxs = nil
}
