// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: notifications.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNotificationConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationConfigRequest) Reset() {
	*x = GetNotificationConfigRequest{}
	mi := &file_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationConfigRequest) ProtoMessage() {}

func (x *GetNotificationConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationConfigRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationConfigRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotificationConfigRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetNotificationConfigRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetNotificationConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationConfigResponse) Reset() {
	*x = GetNotificationConfigResponse{}
	mi := &file_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationConfigResponse) ProtoMessage() {}

func (x *GetNotificationConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationConfigResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationConfigResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *GetNotificationConfigResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetNotificationConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateNotificationConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationConfigRequest) Reset() {
	*x = UpdateNotificationConfigRequest{}
	mi := &file_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationConfigRequest) ProtoMessage() {}

func (x *UpdateNotificationConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationConfigRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateNotificationConfigRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateNotificationConfigRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateNotificationConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationConfigResponse) Reset() {
	*x = UpdateNotificationConfigResponse{}
	mi := &file_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationConfigResponse) ProtoMessage() {}

func (x *UpdateNotificationConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationConfigResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateNotificationConfigResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateNotificationConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_notifications_proto protoreflect.FileDescriptor

const file_notifications_proto_rawDesc = "" +
	"\n" +
	"\x13notifications.proto\"\xb0\x01\n" +
	"\x1cGetNotificationConfigRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12A\n" +
	"\x06config\x18\x02 \x03(\v2).GetNotificationConfigRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x1dGetNotificationConfigResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12B\n" +
	"\x06config\x18\x02 \x03(\v2*.GetNotificationConfigResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x1fUpdateNotificationConfigRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12D\n" +
	"\x06config\x18\x02 \x03(\v2,.UpdateNotificationConfigRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	" UpdateNotificationConfigResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12E\n" +
	"\x06config\x18\x02 \x03(\v2-.UpdateNotificationConfigResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc3\x01\n" +
	"\x13NotificationService\x12Q\n" +
	"\x10GetNotifications\x12\x1d.GetNotificationConfigRequest\x1a\x1e.GetNotificationConfigResponse\x12Y\n" +
	"\x12UpdateNotification\x12 .UpdateNotificationConfigRequest\x1a!.UpdateNotificationConfigResponseB\x1eZ\x1cgithub.com/kvbo/protobufs;pbb\x06proto3"

var (
	file_notifications_proto_rawDescOnce sync.Once
	file_notifications_proto_rawDescData []byte
)

func file_notifications_proto_rawDescGZIP() []byte {
	file_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)))
	})
	return file_notifications_proto_rawDescData
}

var file_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notifications_proto_goTypes = []any{
	(*GetNotificationConfigRequest)(nil),     // 0: GetNotificationConfigRequest
	(*GetNotificationConfigResponse)(nil),    // 1: GetNotificationConfigResponse
	(*UpdateNotificationConfigRequest)(nil),  // 2: UpdateNotificationConfigRequest
	(*UpdateNotificationConfigResponse)(nil), // 3: UpdateNotificationConfigResponse
	nil,                                      // 4: GetNotificationConfigRequest.ConfigEntry
	nil,                                      // 5: GetNotificationConfigResponse.ConfigEntry
	nil,                                      // 6: UpdateNotificationConfigRequest.ConfigEntry
	nil,                                      // 7: UpdateNotificationConfigResponse.ConfigEntry
}
var file_notifications_proto_depIdxs = []int32{
	4, // 0: GetNotificationConfigRequest.config:type_name -> GetNotificationConfigRequest.ConfigEntry
	5, // 1: GetNotificationConfigResponse.config:type_name -> GetNotificationConfigResponse.ConfigEntry
	6, // 2: UpdateNotificationConfigRequest.config:type_name -> UpdateNotificationConfigRequest.ConfigEntry
	7, // 3: UpdateNotificationConfigResponse.config:type_name -> UpdateNotificationConfigResponse.ConfigEntry
	0, // 4: NotificationService.GetNotifications:input_type -> GetNotificationConfigRequest
	2, // 5: NotificationService.UpdateNotification:input_type -> UpdateNotificationConfigRequest
	1, // 6: NotificationService.GetNotifications:output_type -> GetNotificationConfigResponse
	3, // 7: NotificationService.UpdateNotification:output_type -> UpdateNotificationConfigResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_notifications_proto_init() }
func file_notifications_proto_init() {
	if File_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_proto_depIdxs,
		MessageInfos:      file_notifications_proto_msgTypes,
	}.Build()
	File_notifications_proto = out.File
	file_notifications_proto_goTypes = nil
	file_notifications_proto_depIdxs = nil
}
