// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: services.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	MinAmount     int64                  `protobuf:"varint,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     int64                  `protobuf:"varint,5,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Img           string                 `protobuf:"bytes,7,opt,name=img,proto3" json:"img,omitempty"`
	Reversible    bool                   `protobuf:"varint,8,opt,name=reversible,proto3" json:"reversible,omitempty"`
	ChargeIds     []string               `protobuf:"bytes,9,rep,name=charge_ids,json=chargeIds,proto3" json:"charge_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Service) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *Service) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *Service) GetReversible() bool {
	if x != nil {
		return x.Reversible
	}
	return false
}

func (x *Service) GetChargeIds() []string {
	if x != nil {
		return x.ChargeIds
	}
	return nil
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Query         *ServiceQuery          `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateServiceRequest) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *UpdateServiceRequest) GetQuery() *ServiceQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Query         *ServiceQuery          `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceList) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServiceList) GetQuery() *ServiceQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type ServiceQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceQuery) Reset() {
	*x = ServiceQuery{}
	mi := &file_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceQuery) ProtoMessage() {}

func (x *ServiceQuery) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceQuery.ProtoReflect.Descriptor instead.
func (*ServiceQuery) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceQuery) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ServiceQuery) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type AddRemoveFees struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeIds        []string               `protobuf:"bytes,1,rep,name=fee_ids,json=feeIds,proto3" json:"fee_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRemoveFees) Reset() {
	*x = AddRemoveFees{}
	mi := &file_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRemoveFees) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemoveFees) ProtoMessage() {}

func (x *AddRemoveFees) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemoveFees.ProtoReflect.Descriptor instead.
func (*AddRemoveFees) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{4}
}

func (x *AddRemoveFees) GetFeeIds() []string {
	if x != nil {
		return x.FeeIds
	}
	return nil
}

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\"\xf2\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\x03R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x05 \x01(\x03R\tmaxAmount\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x10\n" +
	"\x03img\x18\a \x01(\tR\x03img\x12\x1e\n" +
	"\n" +
	"reversible\x18\b \x01(\bR\n" +
	"reversible\x12\x1d\n" +
	"\n" +
	"charge_ids\x18\t \x03(\tR\tchargeIds\"a\n" +
	"\x14UpdateServiceRequest\x12$\n" +
	"\bservices\x18\x01 \x03(\v2\b.ServiceR\bservices\x12#\n" +
	"\x05query\x18\x02 \x01(\v2\r.ServiceQueryR\x05query\"X\n" +
	"\vServiceList\x12$\n" +
	"\bservices\x18\x01 \x03(\v2\b.ServiceR\bservices\x12#\n" +
	"\x05query\x18\x02 \x01(\v2\r.ServiceQueryR\x05query\"=\n" +
	"\fServiceQuery\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"(\n" +
	"\rAddRemoveFees\x12\x17\n" +
	"\afee_ids\x18\x01 \x03(\tR\x06feeIds2\xd0\x02\n" +
	"\x0eServiceManager\x12#\n" +
	"\rCreateService\x12\b.Service\x1a\b.Service\x124\n" +
	"\rUpdateService\x12\x15.UpdateServiceRequest\x1a\f.ServiceList\x12 \n" +
	"\n" +
	"GetService\x12\b.Service\x1a\b.Service\x12*\n" +
	"\vGetServices\x12\r.ServiceQuery\x1a\f.ServiceList\x12,\n" +
	"\rDeleteService\x12\r.ServiceQuery\x1a\f.ServiceList\x121\n" +
	"\x0fAddFeeToService\x12\x0e.AddRemoveFees\x1a\x0e.AddRemoveFees\x124\n" +
	"\x12RemoveFeeToService\x12\x0e.AddRemoveFees\x1a\x0e.AddRemoveFeesB\x1eZ\x1cgithub.com/kvbo/protobufs;pbb\x06proto3"

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData []byte
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)))
	})
	return file_services_proto_rawDescData
}

var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_services_proto_goTypes = []any{
	(*Service)(nil),              // 0: Service
	(*UpdateServiceRequest)(nil), // 1: UpdateServiceRequest
	(*ServiceList)(nil),          // 2: ServiceList
	(*ServiceQuery)(nil),         // 3: ServiceQuery
	(*AddRemoveFees)(nil),        // 4: AddRemoveFees
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: UpdateServiceRequest.services:type_name -> Service
	3,  // 1: UpdateServiceRequest.query:type_name -> ServiceQuery
	0,  // 2: ServiceList.services:type_name -> Service
	3,  // 3: ServiceList.query:type_name -> ServiceQuery
	0,  // 4: ServiceManager.CreateService:input_type -> Service
	1,  // 5: ServiceManager.UpdateService:input_type -> UpdateServiceRequest
	0,  // 6: ServiceManager.GetService:input_type -> Service
	3,  // 7: ServiceManager.GetServices:input_type -> ServiceQuery
	3,  // 8: ServiceManager.DeleteService:input_type -> ServiceQuery
	4,  // 9: ServiceManager.AddFeeToService:input_type -> AddRemoveFees
	4,  // 10: ServiceManager.RemoveFeeToService:input_type -> AddRemoveFees
	0,  // 11: ServiceManager.CreateService:output_type -> Service
	2,  // 12: ServiceManager.UpdateService:output_type -> ServiceList
	0,  // 13: ServiceManager.GetService:output_type -> Service
	2,  // 14: ServiceManager.GetServices:output_type -> ServiceList
	2,  // 15: ServiceManager.DeleteService:output_type -> ServiceList
	4,  // 16: ServiceManager.AddFeeToService:output_type -> AddRemoveFees
	4,  // 17: ServiceManager.RemoveFeeToService:output_type -> AddRemoveFees
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
