// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: transactions.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionService_InternalTransaction_FullMethodName           = "/TransactionService/InternalTransaction"
	TransactionService_FromExternalTransction_FullMethodName        = "/TransactionService/FromExternalTransction"
	TransactionService_ToExternalTransactionInitiate_FullMethodName = "/TransactionService/ToExternalTransactionInitiate"
	TransactionService_ToExternalTransactionComplete_FullMethodName = "/TransactionService/ToExternalTransactionComplete"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	InternalTransaction(ctx context.Context, in *TransactionIn, opts ...grpc.CallOption) (*TransactionOut, error)
	FromExternalTransction(ctx context.Context, in *TransactionIn, opts ...grpc.CallOption) (*TransactionOut, error)
	ToExternalTransactionInitiate(ctx context.Context, in *TransactionIn, opts ...grpc.CallOption) (*TransactionOut, error)
	ToExternalTransactionComplete(ctx context.Context, in *TransactionIn, opts ...grpc.CallOption) (*TransactionOut, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) InternalTransaction(ctx context.Context, in *TransactionIn, opts ...grpc.CallOption) (*TransactionOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionOut)
	err := c.cc.Invoke(ctx, TransactionService_InternalTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FromExternalTransction(ctx context.Context, in *TransactionIn, opts ...grpc.CallOption) (*TransactionOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionOut)
	err := c.cc.Invoke(ctx, TransactionService_FromExternalTransction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ToExternalTransactionInitiate(ctx context.Context, in *TransactionIn, opts ...grpc.CallOption) (*TransactionOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionOut)
	err := c.cc.Invoke(ctx, TransactionService_ToExternalTransactionInitiate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ToExternalTransactionComplete(ctx context.Context, in *TransactionIn, opts ...grpc.CallOption) (*TransactionOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionOut)
	err := c.cc.Invoke(ctx, TransactionService_ToExternalTransactionComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
type TransactionServiceServer interface {
	InternalTransaction(context.Context, *TransactionIn) (*TransactionOut, error)
	FromExternalTransction(context.Context, *TransactionIn) (*TransactionOut, error)
	ToExternalTransactionInitiate(context.Context, *TransactionIn) (*TransactionOut, error)
	ToExternalTransactionComplete(context.Context, *TransactionIn) (*TransactionOut, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) InternalTransaction(context.Context, *TransactionIn) (*TransactionOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) FromExternalTransction(context.Context, *TransactionIn) (*TransactionOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FromExternalTransction not implemented")
}
func (UnimplementedTransactionServiceServer) ToExternalTransactionInitiate(context.Context, *TransactionIn) (*TransactionOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToExternalTransactionInitiate not implemented")
}
func (UnimplementedTransactionServiceServer) ToExternalTransactionComplete(context.Context, *TransactionIn) (*TransactionOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToExternalTransactionComplete not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_InternalTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).InternalTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_InternalTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).InternalTransaction(ctx, req.(*TransactionIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FromExternalTransction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FromExternalTransction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FromExternalTransction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FromExternalTransction(ctx, req.(*TransactionIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ToExternalTransactionInitiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ToExternalTransactionInitiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ToExternalTransactionInitiate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ToExternalTransactionInitiate(ctx, req.(*TransactionIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ToExternalTransactionComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ToExternalTransactionComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ToExternalTransactionComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ToExternalTransactionComplete(ctx, req.(*TransactionIn))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalTransaction",
			Handler:    _TransactionService_InternalTransaction_Handler,
		},
		{
			MethodName: "FromExternalTransction",
			Handler:    _TransactionService_FromExternalTransction_Handler,
		},
		{
			MethodName: "ToExternalTransactionInitiate",
			Handler:    _TransactionService_ToExternalTransactionInitiate_Handler,
		},
		{
			MethodName: "ToExternalTransactionComplete",
			Handler:    _TransactionService_ToExternalTransactionComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions.proto",
}
