// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: transactions.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Embedded Summary message
type Summary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AmountRecieved    int64                  `protobuf:"varint,1,opt,name=amount_recieved,json=amountRecieved,proto3" json:"amount_recieved,omitempty"`
	AmountSent        int64                  `protobuf:"varint,2,opt,name=amount_sent,json=amountSent,proto3" json:"amount_sent,omitempty"`
	TotalCharges      int64                  `protobuf:"varint,3,opt,name=total_charges,json=totalCharges,proto3" json:"total_charges,omitempty"`
	CostToBusiness    int64                  `protobuf:"varint,4,opt,name=cost_to_business,json=costToBusiness,proto3" json:"cost_to_business,omitempty"`
	SourceCharge      int64                  `protobuf:"varint,5,opt,name=source_charge,json=sourceCharge,proto3" json:"source_charge,omitempty"`
	DestinationCharge int64                  `protobuf:"varint,6,opt,name=destination_charge,json=destinationCharge,proto3" json:"destination_charge,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *Summary) GetAmountRecieved() int64 {
	if x != nil {
		return x.AmountRecieved
	}
	return 0
}

func (x *Summary) GetAmountSent() int64 {
	if x != nil {
		return x.AmountSent
	}
	return 0
}

func (x *Summary) GetTotalCharges() int64 {
	if x != nil {
		return x.TotalCharges
	}
	return 0
}

func (x *Summary) GetCostToBusiness() int64 {
	if x != nil {
		return x.CostToBusiness
	}
	return 0
}

func (x *Summary) GetSourceCharge() int64 {
	if x != nil {
		return x.SourceCharge
	}
	return 0
}

func (x *Summary) GetDestinationCharge() int64 {
	if x != nil {
		return x.DestinationCharge
	}
	return 0
}

// Main TransactionOut message
type Transaction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // equivalent to Model.ExtID in BeforeCreate
	Ref                  string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ServiceId            *string                `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3,oneof" json:"service_id,omitempty"`
	SourceAccountId      string                 `protobuf:"bytes,7,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DestinationAccountId string                 `protobuf:"bytes,8,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	Service              *Service               `protobuf:"bytes,9,opt,name=service,proto3,oneof" json:"service,omitempty"`
	Source               *string                `protobuf:"bytes,10,opt,name=source,proto3,oneof" json:"source,omitempty"`
	Destination          *string                `protobuf:"bytes,11,opt,name=destination,proto3,oneof" json:"destination,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,12,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Status               string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	InitiatedAt          string                 `protobuf:"bytes,14,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`
	CompletedAt          string                 `protobuf:"bytes,15,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CallbackUrl          string                 `protobuf:"bytes,18,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	Metadata             *structpb.Struct       `protobuf:"bytes,19,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Summary              *Summary               `protobuf:"bytes,20,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetServiceId() string {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return ""
}

func (x *Transaction) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *Transaction) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *Transaction) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Transaction) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Transaction) GetDestination() string {
	if x != nil && x.Destination != nil {
		return *x.Destination
	}
	return ""
}

func (x *Transaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetInitiatedAt() string {
	if x != nil {
		return x.InitiatedAt
	}
	return ""
}

func (x *Transaction) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transaction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Transaction) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *Transaction) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Transaction) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// Create Instant Transaction
type TransactionIn struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Ref                  string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Description          *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Currency             string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ServiceId            *string                `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3,oneof" json:"service_id,omitempty"`
	SourceAccountId      string                 `protobuf:"bytes,6,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DestinationAccountId string                 `protobuf:"bytes,7,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CallbackUrl          *string                `protobuf:"bytes,9,opt,name=callback_url,json=callbackUrl,proto3,oneof" json:"callback_url,omitempty"`
	Metadata             *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransactionIn) Reset() {
	*x = TransactionIn{}
	mi := &file_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionIn) ProtoMessage() {}

func (x *TransactionIn) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionIn.ProtoReflect.Descriptor instead.
func (*TransactionIn) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionIn) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TransactionIn) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *TransactionIn) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionIn) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionIn) GetServiceId() string {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return ""
}

func (x *TransactionIn) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *TransactionIn) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *TransactionIn) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransactionIn) GetCallbackUrl() string {
	if x != nil && x.CallbackUrl != nil {
		return *x.CallbackUrl
	}
	return ""
}

func (x *TransactionIn) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateInstantTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *TransactionIn         `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstantTransactionRequest) Reset() {
	*x = CreateInstantTransactionRequest{}
	mi := &file_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstantTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstantTransactionRequest) ProtoMessage() {}

func (x *CreateInstantTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstantTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateInstantTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *CreateInstantTransactionRequest) GetTransaction() *TransactionIn {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type CreateInstantTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *TransactionIn         `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstantTransactionResponse) Reset() {
	*x = CreateInstantTransactionResponse{}
	mi := &file_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstantTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstantTransactionResponse) ProtoMessage() {}

func (x *CreateInstantTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstantTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateInstantTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInstantTransactionResponse) GetTransaction() *TransactionIn {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Start Transaction
type StartTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *TransactionIn         `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTransactionRequest) Reset() {
	*x = StartTransactionRequest{}
	mi := &file_transactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTransactionRequest) ProtoMessage() {}

func (x *StartTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTransactionRequest.ProtoReflect.Descriptor instead.
func (*StartTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{5}
}

func (x *StartTransactionRequest) GetTransaction() *TransactionIn {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type StartTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTransactionResponse) Reset() {
	*x = StartTransactionResponse{}
	mi := &file_transactions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTransactionResponse) ProtoMessage() {}

func (x *StartTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTransactionResponse.ProtoReflect.Descriptor instead.
func (*StartTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{6}
}

func (x *StartTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Complete Transaction
type CompleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // completed - failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTransactionRequest) Reset() {
	*x = CompleteTransactionRequest{}
	mi := &file_transactions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTransactionRequest) ProtoMessage() {}

func (x *CompleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*CompleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteTransactionRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *CompleteTransactionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CompleteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTransactionResponse) Reset() {
	*x = CompleteTransactionResponse{}
	mi := &file_transactions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTransactionResponse) ProtoMessage() {}

func (x *CompleteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTransactionResponse.ProtoReflect.Descriptor instead.
func (*CompleteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Cancel Transaction
type CancelTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransactionRequest) Reset() {
	*x = CancelTransactionRequest{}
	mi := &file_transactions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransactionRequest) ProtoMessage() {}

func (x *CancelTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransactionRequest.ProtoReflect.Descriptor instead.
func (*CancelTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTransactionRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type CancelTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransactionResponse) Reset() {
	*x = CancelTransactionResponse{}
	mi := &file_transactions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransactionResponse) ProtoMessage() {}

func (x *CancelTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransactionResponse.ProtoReflect.Descriptor instead.
func (*CancelTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Start Reversal
type StartReversalRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Ref                   string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	OriginalTransactionId string                 `protobuf:"bytes,2,opt,name=original_transaction_id,json=originalTransactionId,proto3" json:"original_transaction_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StartReversalRequest) Reset() {
	*x = StartReversalRequest{}
	mi := &file_transactions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReversalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReversalRequest) ProtoMessage() {}

func (x *StartReversalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReversalRequest.ProtoReflect.Descriptor instead.
func (*StartReversalRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{11}
}

func (x *StartReversalRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *StartReversalRequest) GetOriginalTransactionId() string {
	if x != nil {
		return x.OriginalTransactionId
	}
	return ""
}

type StartReversalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReversalResponse) Reset() {
	*x = StartReversalResponse{}
	mi := &file_transactions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReversalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReversalResponse) ProtoMessage() {}

func (x *StartReversalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReversalResponse.ProtoReflect.Descriptor instead.
func (*StartReversalResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{12}
}

func (x *StartReversalResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Complete Reversal
type CompleteReversalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteReversalRequest) Reset() {
	*x = CompleteReversalRequest{}
	mi := &file_transactions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteReversalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteReversalRequest) ProtoMessage() {}

func (x *CompleteReversalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteReversalRequest.ProtoReflect.Descriptor instead.
func (*CompleteReversalRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteReversalRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *CompleteReversalRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CompleteReversalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteReversalResponse) Reset() {
	*x = CompleteReversalResponse{}
	mi := &file_transactions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteReversalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteReversalResponse) ProtoMessage() {}

func (x *CompleteReversalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteReversalResponse.ProtoReflect.Descriptor instead.
func (*CompleteReversalResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{14}
}

func (x *CompleteReversalResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Cancel Reversal
type CancelReversalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReversalRequest) Reset() {
	*x = CancelReversalRequest{}
	mi := &file_transactions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReversalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReversalRequest) ProtoMessage() {}

func (x *CancelReversalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReversalRequest.ProtoReflect.Descriptor instead.
func (*CancelReversalRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{15}
}

func (x *CancelReversalRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type CancelReversalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReversalResponse) Reset() {
	*x = CancelReversalResponse{}
	mi := &file_transactions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReversalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReversalResponse) ProtoMessage() {}

func (x *CancelReversalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReversalResponse.ProtoReflect.Descriptor instead.
func (*CancelReversalResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{16}
}

func (x *CancelReversalResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_transactions_proto protoreflect.FileDescriptor

const file_transactions_proto_rawDesc = "" +
	"\n" +
	"\x12transactions.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0eservices.proto\"\xf6\x01\n" +
	"\aSummary\x12'\n" +
	"\x0famount_recieved\x18\x01 \x01(\x03R\x0eamountRecieved\x12\x1f\n" +
	"\vamount_sent\x18\x02 \x01(\x03R\n" +
	"amountSent\x12#\n" +
	"\rtotal_charges\x18\x03 \x01(\x03R\ftotalCharges\x12(\n" +
	"\x10cost_to_business\x18\x04 \x01(\x03R\x0ecostToBusiness\x12#\n" +
	"\rsource_charge\x18\x05 \x01(\x03R\fsourceCharge\x12-\n" +
	"\x12destination_charge\x18\x06 \x01(\x03R\x11destinationCharge\"\x80\x06\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\"\n" +
	"\n" +
	"service_id\x18\x06 \x01(\tH\x00R\tserviceId\x88\x01\x01\x12*\n" +
	"\x11source_account_id\x18\a \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\b \x01(\tR\x14destinationAccountId\x12'\n" +
	"\aservice\x18\t \x01(\v2\b.ServiceH\x01R\aservice\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\n" +
	" \x01(\tH\x02R\x06source\x88\x01\x01\x12%\n" +
	"\vdestination\x18\v \x01(\tH\x03R\vdestination\x88\x01\x01\x12'\n" +
	"\x0fidempotency_key\x18\f \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12!\n" +
	"\finitiated_at\x18\x0e \x01(\tR\vinitiatedAt\x12!\n" +
	"\fcompleted_at\x18\x0f \x01(\tR\vcompletedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\x12!\n" +
	"\fcallback_url\x18\x12 \x01(\tR\vcallbackUrl\x123\n" +
	"\bmetadata\x18\x13 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12'\n" +
	"\asummary\x18\x14 \x01(\v2\b.SummaryH\x04R\asummary\x88\x01\x01B\r\n" +
	"\v_service_idB\n" +
	"\n" +
	"\b_serviceB\t\n" +
	"\a_sourceB\x0e\n" +
	"\f_destinationB\n" +
	"\n" +
	"\b_summary\"\xb8\x03\n" +
	"\rTransactionIn\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\"\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tH\x01R\tserviceId\x88\x01\x01\x12*\n" +
	"\x11source_account_id\x18\x06 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\a \x01(\tR\x14destinationAccountId\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12&\n" +
	"\fcallback_url\x18\t \x01(\tH\x02R\vcallbackUrl\x88\x01\x01\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadataB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_service_idB\x0f\n" +
	"\r_callback_url\"S\n" +
	"\x1fCreateInstantTransactionRequest\x120\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0e.TransactionInR\vtransaction\"T\n" +
	" CreateInstantTransactionResponse\x120\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0e.TransactionInR\vtransaction\"K\n" +
	"\x17StartTransactionRequest\x120\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0e.TransactionInR\vtransaction\"J\n" +
	"\x18StartTransactionResponse\x12.\n" +
	"\vtransaction\x18\x01 \x01(\v2\f.TransactionR\vtransaction\"F\n" +
	"\x1aCompleteTransactionRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"M\n" +
	"\x1bCompleteTransactionResponse\x12.\n" +
	"\vtransaction\x18\x01 \x01(\v2\f.TransactionR\vtransaction\",\n" +
	"\x18CancelTransactionRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"K\n" +
	"\x19CancelTransactionResponse\x12.\n" +
	"\vtransaction\x18\x01 \x01(\v2\f.TransactionR\vtransaction\"`\n" +
	"\x14StartReversalRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x126\n" +
	"\x17original_transaction_id\x18\x02 \x01(\tR\x15originalTransactionId\"G\n" +
	"\x15StartReversalResponse\x12.\n" +
	"\vtransaction\x18\x01 \x01(\v2\f.TransactionR\vtransaction\"C\n" +
	"\x17CompleteReversalRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"J\n" +
	"\x18CompleteReversalResponse\x12.\n" +
	"\vtransaction\x18\x01 \x01(\v2\f.TransactionR\vtransaction\")\n" +
	"\x15CancelReversalRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"H\n" +
	"\x16CancelReversalResponse\x12.\n" +
	"\vtransaction\x18\x01 \x01(\v2\f.TransactionR\vtransaction2\xa8\x04\n" +
	"\x12TransactionService\x12_\n" +
	"\x18CreateInstantTransaction\x12 .CreateInstantTransactionRequest\x1a!.CreateInstantTransactionResponse\x12G\n" +
	"\x10StartTransaction\x12\x18.StartTransactionRequest\x1a\x19.StartTransactionResponse\x12P\n" +
	"\x13CompleteTransaction\x12\x1b.CompleteTransactionRequest\x1a\x1c.CompleteTransactionResponse\x12J\n" +
	"\x11CancelTransaction\x12\x19.CancelTransactionRequest\x1a\x1a.CancelTransactionResponse\x12>\n" +
	"\rStartReversal\x12\x15.StartReversalRequest\x1a\x16.StartReversalResponse\x12G\n" +
	"\x10CompleteReversal\x12\x18.CompleteReversalRequest\x1a\x19.CompleteReversalResponse\x12A\n" +
	"\x0eCancelReversal\x12\x16.CancelReversalRequest\x1a\x17.CancelReversalResponseB\x1eZ\x1cgithub.com/kvbo/protobufs;pbb\x06proto3"

var (
	file_transactions_proto_rawDescOnce sync.Once
	file_transactions_proto_rawDescData []byte
)

func file_transactions_proto_rawDescGZIP() []byte {
	file_transactions_proto_rawDescOnce.Do(func() {
		file_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transactions_proto_rawDesc), len(file_transactions_proto_rawDesc)))
	})
	return file_transactions_proto_rawDescData
}

var file_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_transactions_proto_goTypes = []any{
	(*Summary)(nil),                          // 0: Summary
	(*Transaction)(nil),                      // 1: Transaction
	(*TransactionIn)(nil),                    // 2: TransactionIn
	(*CreateInstantTransactionRequest)(nil),  // 3: CreateInstantTransactionRequest
	(*CreateInstantTransactionResponse)(nil), // 4: CreateInstantTransactionResponse
	(*StartTransactionRequest)(nil),          // 5: StartTransactionRequest
	(*StartTransactionResponse)(nil),         // 6: StartTransactionResponse
	(*CompleteTransactionRequest)(nil),       // 7: CompleteTransactionRequest
	(*CompleteTransactionResponse)(nil),      // 8: CompleteTransactionResponse
	(*CancelTransactionRequest)(nil),         // 9: CancelTransactionRequest
	(*CancelTransactionResponse)(nil),        // 10: CancelTransactionResponse
	(*StartReversalRequest)(nil),             // 11: StartReversalRequest
	(*StartReversalResponse)(nil),            // 12: StartReversalResponse
	(*CompleteReversalRequest)(nil),          // 13: CompleteReversalRequest
	(*CompleteReversalResponse)(nil),         // 14: CompleteReversalResponse
	(*CancelReversalRequest)(nil),            // 15: CancelReversalRequest
	(*CancelReversalResponse)(nil),           // 16: CancelReversalResponse
	(*Service)(nil),                          // 17: Service
	(*structpb.Struct)(nil),                  // 18: google.protobuf.Struct
}
var file_transactions_proto_depIdxs = []int32{
	17, // 0: Transaction.service:type_name -> Service
	18, // 1: Transaction.metadata:type_name -> google.protobuf.Struct
	0,  // 2: Transaction.summary:type_name -> Summary
	18, // 3: TransactionIn.metadata:type_name -> google.protobuf.Struct
	2,  // 4: CreateInstantTransactionRequest.transaction:type_name -> TransactionIn
	2,  // 5: CreateInstantTransactionResponse.transaction:type_name -> TransactionIn
	2,  // 6: StartTransactionRequest.transaction:type_name -> TransactionIn
	1,  // 7: StartTransactionResponse.transaction:type_name -> Transaction
	1,  // 8: CompleteTransactionResponse.transaction:type_name -> Transaction
	1,  // 9: CancelTransactionResponse.transaction:type_name -> Transaction
	1,  // 10: StartReversalResponse.transaction:type_name -> Transaction
	1,  // 11: CompleteReversalResponse.transaction:type_name -> Transaction
	1,  // 12: CancelReversalResponse.transaction:type_name -> Transaction
	3,  // 13: TransactionService.CreateInstantTransaction:input_type -> CreateInstantTransactionRequest
	5,  // 14: TransactionService.StartTransaction:input_type -> StartTransactionRequest
	7,  // 15: TransactionService.CompleteTransaction:input_type -> CompleteTransactionRequest
	9,  // 16: TransactionService.CancelTransaction:input_type -> CancelTransactionRequest
	11, // 17: TransactionService.StartReversal:input_type -> StartReversalRequest
	13, // 18: TransactionService.CompleteReversal:input_type -> CompleteReversalRequest
	15, // 19: TransactionService.CancelReversal:input_type -> CancelReversalRequest
	4,  // 20: TransactionService.CreateInstantTransaction:output_type -> CreateInstantTransactionResponse
	6,  // 21: TransactionService.StartTransaction:output_type -> StartTransactionResponse
	8,  // 22: TransactionService.CompleteTransaction:output_type -> CompleteTransactionResponse
	10, // 23: TransactionService.CancelTransaction:output_type -> CancelTransactionResponse
	12, // 24: TransactionService.StartReversal:output_type -> StartReversalResponse
	14, // 25: TransactionService.CompleteReversal:output_type -> CompleteReversalResponse
	16, // 26: TransactionService.CancelReversal:output_type -> CancelReversalResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_transactions_proto_init() }
func file_transactions_proto_init() {
	if File_transactions_proto != nil {
		return
	}
	file_services_proto_init()
	file_transactions_proto_msgTypes[1].OneofWrappers = []any{}
	file_transactions_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transactions_proto_rawDesc), len(file_transactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transactions_proto_goTypes,
		DependencyIndexes: file_transactions_proto_depIdxs,
		MessageInfos:      file_transactions_proto_msgTypes,
	}.Build()
	File_transactions_proto = out.File
	file_transactions_proto_goTypes = nil
	file_transactions_proto_depIdxs = nil
}
