// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: transactions.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Embedded Summary message
type Summary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AmountRecieved    int64                  `protobuf:"varint,1,opt,name=amount_recieved,json=amountRecieved,proto3" json:"amount_recieved,omitempty"`
	AmountSent        int64                  `protobuf:"varint,2,opt,name=amount_sent,json=amountSent,proto3" json:"amount_sent,omitempty"`
	TotalCharges      int64                  `protobuf:"varint,3,opt,name=total_charges,json=totalCharges,proto3" json:"total_charges,omitempty"`
	CostToBusiness    int64                  `protobuf:"varint,4,opt,name=cost_to_business,json=costToBusiness,proto3" json:"cost_to_business,omitempty"`
	SourceCharge      int64                  `protobuf:"varint,5,opt,name=source_charge,json=sourceCharge,proto3" json:"source_charge,omitempty"`
	DestinationCharge int64                  `protobuf:"varint,6,opt,name=destination_charge,json=destinationCharge,proto3" json:"destination_charge,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *Summary) GetAmountRecieved() int64 {
	if x != nil {
		return x.AmountRecieved
	}
	return 0
}

func (x *Summary) GetAmountSent() int64 {
	if x != nil {
		return x.AmountSent
	}
	return 0
}

func (x *Summary) GetTotalCharges() int64 {
	if x != nil {
		return x.TotalCharges
	}
	return 0
}

func (x *Summary) GetCostToBusiness() int64 {
	if x != nil {
		return x.CostToBusiness
	}
	return 0
}

func (x *Summary) GetSourceCharge() int64 {
	if x != nil {
		return x.SourceCharge
	}
	return 0
}

func (x *Summary) GetDestinationCharge() int64 {
	if x != nil {
		return x.DestinationCharge
	}
	return 0
}

// Main TransactionOut message
type TransactionOut struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // equivalent to Model.ExtID in BeforeCreate
	Ref                  string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ServiceId            string                 `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	SourceAccountId      string                 `protobuf:"bytes,7,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DestinationAccountId string                 `protobuf:"bytes,8,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	Service              *structpb.Struct       `protobuf:"bytes,9,opt,name=service,proto3" json:"service,omitempty"`
	Source               *structpb.Struct       `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	Destination          *structpb.Struct       `protobuf:"bytes,11,opt,name=destination,proto3" json:"destination,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,12,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Status               string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	InitiatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CallbackUrl          string                 `protobuf:"bytes,18,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	Metadata             *structpb.Struct       `protobuf:"bytes,19,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Summary              *Summary               `protobuf:"bytes,20,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransactionOut) Reset() {
	*x = TransactionOut{}
	mi := &file_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionOut) ProtoMessage() {}

func (x *TransactionOut) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionOut.ProtoReflect.Descriptor instead.
func (*TransactionOut) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionOut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionOut) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TransactionOut) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionOut) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionOut) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionOut) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *TransactionOut) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *TransactionOut) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *TransactionOut) GetService() *structpb.Struct {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *TransactionOut) GetSource() *structpb.Struct {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TransactionOut) GetDestination() *structpb.Struct {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *TransactionOut) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransactionOut) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionOut) GetInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitiatedAt
	}
	return nil
}

func (x *TransactionOut) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TransactionOut) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransactionOut) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TransactionOut) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *TransactionOut) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TransactionOut) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type TransactionIn struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Ref                  string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Currency             string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Service              *Service               `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	SourceAccountId      string                 `protobuf:"bytes,6,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DestinationAccountId string                 `protobuf:"bytes,7,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CallbackUrl          string                 `protobuf:"bytes,9,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	Metadata             *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransactionIn) Reset() {
	*x = TransactionIn{}
	mi := &file_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionIn) ProtoMessage() {}

func (x *TransactionIn) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionIn.ProtoReflect.Descriptor instead.
func (*TransactionIn) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionIn) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TransactionIn) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionIn) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionIn) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionIn) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *TransactionIn) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *TransactionIn) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *TransactionIn) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransactionIn) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *TransactionIn) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_transactions_proto protoreflect.FileDescriptor

const file_transactions_proto_rawDesc = "" +
	"\n" +
	"\x12transactions.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0eservices.proto\"\xf6\x01\n" +
	"\aSummary\x12'\n" +
	"\x0famount_recieved\x18\x01 \x01(\x03R\x0eamountRecieved\x12\x1f\n" +
	"\vamount_sent\x18\x02 \x01(\x03R\n" +
	"amountSent\x12#\n" +
	"\rtotal_charges\x18\x03 \x01(\x03R\ftotalCharges\x12(\n" +
	"\x10cost_to_business\x18\x04 \x01(\x03R\x0ecostToBusiness\x12#\n" +
	"\rsource_charge\x18\x05 \x01(\x03R\fsourceCharge\x12-\n" +
	"\x12destination_charge\x18\x06 \x01(\x03R\x11destinationCharge\"\xd9\x06\n" +
	"\x0eTransactionOut\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"service_id\x18\x06 \x01(\tR\tserviceId\x12*\n" +
	"\x11source_account_id\x18\a \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\b \x01(\tR\x14destinationAccountId\x121\n" +
	"\aservice\x18\t \x01(\v2\x17.google.protobuf.StructR\aservice\x12/\n" +
	"\x06source\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x06source\x129\n" +
	"\vdestination\x18\v \x01(\v2\x17.google.protobuf.StructR\vdestination\x12'\n" +
	"\x0fidempotency_key\x18\f \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12=\n" +
	"\finitiated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vinitiatedAt\x12=\n" +
	"\fcompleted_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12!\n" +
	"\fcallback_url\x18\x12 \x01(\tR\vcallbackUrl\x123\n" +
	"\bmetadata\x18\x13 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\"\n" +
	"\asummary\x18\x14 \x01(\v2\b.SummaryR\asummary\"\xfe\x02\n" +
	"\rTransactionIn\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\"\n" +
	"\aservice\x18\x05 \x01(\v2\b.ServiceR\aservice\x12*\n" +
	"\x11source_account_id\x18\x06 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\a \x01(\tR\x14destinationAccountId\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\fcallback_url\x18\t \x01(\tR\vcallbackUrl\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata2\x8b\x03\n" +
	"\x12TransactionService\x126\n" +
	"\x13InternalTransaction\x12\x0e.TransactionIn\x1a\x0f.TransactionOut\x129\n" +
	"\x16FromExternalTransction\x12\x0e.TransactionIn\x1a\x0f.TransactionOut\x12>\n" +
	"\x1bInternalTransactionInitiate\x12\x0e.TransactionIn\x1a\x0f.TransactionOut\x12>\n" +
	"\x1bInternalTransactionComplete\x12\x0e.TransactionIn\x1a\x0f.TransactionOut\x12@\n" +
	"\x1dToExternalTransactionInitiate\x12\x0e.TransactionIn\x1a\x0f.TransactionOut\x12@\n" +
	"\x1dToExternalTransactionComplete\x12\x0e.TransactionIn\x1a\x0f.TransactionOutB\x1eZ\x1cgithub.com/kvbo/protobufs;pbb\x06proto3"

var (
	file_transactions_proto_rawDescOnce sync.Once
	file_transactions_proto_rawDescData []byte
)

func file_transactions_proto_rawDescGZIP() []byte {
	file_transactions_proto_rawDescOnce.Do(func() {
		file_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transactions_proto_rawDesc), len(file_transactions_proto_rawDesc)))
	})
	return file_transactions_proto_rawDescData
}

var file_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transactions_proto_goTypes = []any{
	(*Summary)(nil),               // 0: Summary
	(*TransactionOut)(nil),        // 1: TransactionOut
	(*TransactionIn)(nil),         // 2: TransactionIn
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Service)(nil),               // 5: Service
}
var file_transactions_proto_depIdxs = []int32{
	3,  // 0: TransactionOut.service:type_name -> google.protobuf.Struct
	3,  // 1: TransactionOut.source:type_name -> google.protobuf.Struct
	3,  // 2: TransactionOut.destination:type_name -> google.protobuf.Struct
	4,  // 3: TransactionOut.initiated_at:type_name -> google.protobuf.Timestamp
	4,  // 4: TransactionOut.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 5: TransactionOut.created_at:type_name -> google.protobuf.Timestamp
	4,  // 6: TransactionOut.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 7: TransactionOut.metadata:type_name -> google.protobuf.Struct
	0,  // 8: TransactionOut.summary:type_name -> Summary
	5,  // 9: TransactionIn.service:type_name -> Service
	3,  // 10: TransactionIn.metadata:type_name -> google.protobuf.Struct
	2,  // 11: TransactionService.InternalTransaction:input_type -> TransactionIn
	2,  // 12: TransactionService.FromExternalTransction:input_type -> TransactionIn
	2,  // 13: TransactionService.InternalTransactionInitiate:input_type -> TransactionIn
	2,  // 14: TransactionService.InternalTransactionComplete:input_type -> TransactionIn
	2,  // 15: TransactionService.ToExternalTransactionInitiate:input_type -> TransactionIn
	2,  // 16: TransactionService.ToExternalTransactionComplete:input_type -> TransactionIn
	1,  // 17: TransactionService.InternalTransaction:output_type -> TransactionOut
	1,  // 18: TransactionService.FromExternalTransction:output_type -> TransactionOut
	1,  // 19: TransactionService.InternalTransactionInitiate:output_type -> TransactionOut
	1,  // 20: TransactionService.InternalTransactionComplete:output_type -> TransactionOut
	1,  // 21: TransactionService.ToExternalTransactionInitiate:output_type -> TransactionOut
	1,  // 22: TransactionService.ToExternalTransactionComplete:output_type -> TransactionOut
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_transactions_proto_init() }
func file_transactions_proto_init() {
	if File_transactions_proto != nil {
		return
	}
	file_services_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transactions_proto_rawDesc), len(file_transactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transactions_proto_goTypes,
		DependencyIndexes: file_transactions_proto_depIdxs,
		MessageInfos:      file_transactions_proto_msgTypes,
	}.Build()
	File_transactions_proto = out.File
	file_transactions_proto_goTypes = nil
	file_transactions_proto_depIdxs = nil
}
